export default [
  {
    language: 'any',
    source: '...uidsog h29 g34',
    tokens: [
      {index: 0, value: '', break: '.'},
      {index: 1, value: '', break: '.'},
      {index: 2, value: '', break: '.'},
      {index: 3, value: 'uidsog', break: ' '},
      {index: 10, value: 'h29', break: ' '},
      {index: 14, value: 'g34', break: ''},
    ],
  },
  {
    language: 'english',
    source:
      "Math Problem: The parking lot at a grocery store has 90 cars in it (30% of the cars are two-toned). How many cars are two-toned? After 5 hours, the 2 cars are 2,750.5 km apart. Find the speed of each car? Tip! The second car was driven by Sgt. Grant's son.",
    tokens: [
      {index: 0, value: 'Math', break: ' '},
      {index: 5, value: 'Problem', break: ':'},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'The', break: ' '},
      {index: 18, value: 'parking', break: ' '},
      {index: 26, value: 'lot', break: ' '},
      {index: 30, value: 'at', break: ' '},
      {index: 33, value: 'a', break: ' '},
      {index: 35, value: 'grocery', break: ' '},
      {index: 43, value: 'store', break: ' '},
      {index: 49, value: 'has', break: ' '},
      {index: 53, value: '90', break: ' '},
      {index: 56, value: 'cars', break: ' '},
      {index: 61, value: 'in', break: ' '},
      {index: 64, value: 'it', break: ' '},
      {index: 67, value: '', break: '('},
      {index: 68, value: '30', break: '%'},
      {index: 71, value: '', break: ' '},
      {index: 72, value: 'of', break: ' '},
      {index: 75, value: 'the', break: ' '},
      {index: 79, value: 'cars', break: ' '},
      {index: 84, value: 'are', break: ' '},
      {index: 88, value: 'two', break: '-'},
      {index: 92, value: 'toned', break: ')'},
      {index: 98, value: '', break: '.'},
      {index: 99, value: '', break: ' '},
      {index: 100, value: 'How', break: ' '},
      {index: 104, value: 'many', break: ' '},
      {index: 109, value: 'cars', break: ' '},
      {index: 114, value: 'are', break: ' '},
      {index: 118, value: 'two', break: '-'},
      {index: 122, value: 'toned', break: '?'},
      {index: 128, value: '', break: ' '},
      {index: 129, value: 'After', break: ' '},
      {index: 135, value: '5', break: ' '},
      {index: 137, value: 'hours', break: ','},
      {index: 143, value: '', break: ' '},
      {index: 144, value: 'the', break: ' '},
      {index: 148, value: '2', break: ' '},
      {index: 150, value: 'cars', break: ' '},
      {index: 155, value: 'are', break: ' '},
      {index: 159, value: '2', break: ','},
      {index: 161, value: '750', break: '.'},
      {index: 165, value: '5', break: ' '},
      {index: 167, value: 'km', break: ' '},
      {index: 170, value: 'apart', break: '.'},
      {index: 176, value: '', break: ' '},
      {index: 177, value: 'Find', break: ' '},
      {index: 182, value: 'the', break: ' '},
      {index: 186, value: 'speed', break: ' '},
      {index: 192, value: 'of', break: ' '},
      {index: 195, value: 'each', break: ' '},
      {index: 200, value: 'car', break: '?'},
      {index: 204, value: '', break: ' '},
      {index: 205, value: 'Tip', break: '!'},
      {index: 209, value: '', break: ' '},
      {index: 210, value: 'The', break: ' '},
      {index: 214, value: 'second', break: ' '},
      {index: 221, value: 'car', break: ' '},
      {index: 225, value: 'was', break: ' '},
      {index: 229, value: 'driven', break: ' '},
      {index: 236, value: 'by', break: ' '},
      {index: 239, value: 'Sgt', break: '.'},
      {index: 243, value: '', break: ' '},
      {index: 244, value: 'Grant', break: "'"},
      {index: 250, value: 's', break: ' '},
      {index: 252, value: 'son', break: '.'},
    ],
  },
] as const;
