// Weekly users by language
// https://docs.google.com/spreadsheets/d/1CGYlgdZq3x_Ti1n_l-m0Qc4BhsIoHv_AjjMhlbdxrZ4
// https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

export default [
  {
    scenario: 'random',
    source: '.,!uidsog: !@foo $%^adg &*(asd)',
    tokens: [
      {index: 0, value: '', break: '.'},
      {index: 1, value: '', break: ','},
      {index: 2, value: '', break: '!'},
      {index: 3, value: 'uidsog', break: ':'},
      {index: 10, value: '', break: ' '},
      {index: 11, value: '', break: '!'},
      {index: 12, value: '', break: '@'},
      {index: 13, value: 'foo', break: ' '},
      {index: 17, value: '', break: '$'},
      {index: 18, value: '', break: '%'},
      {index: 19, value: '', break: '^'},
      {index: 20, value: 'adg', break: ' '},
      {index: 24, value: '', break: '&'},
      {index: 25, value: '', break: '*'},
      {index: 26, value: '', break: '('},
      {index: 27, value: 'asd', break: ')'},
    ],
  },
  {
    scenario: 'quotation marks',
    source: `–‚‘’„“”«»‹›`,
    tokens: [
      {index: 0, value: '', break: '–'},
      {index: 1, value: '', break: '‚'},
      {index: 2, value: '', break: '‘'},
      {index: 3, value: '', break: '’'},
      {index: 4, value: '', break: '„'},
      {index: 5, value: '', break: '“'},
      {index: 6, value: '', break: '”'},
      {index: 7, value: '', break: '«'},
      {index: 8, value: '', break: '»'},
      {index: 9, value: '', break: '‹'},
      {index: 10, value: '', break: '›'},
    ],
  },
  {
    scenario: 'math',
    source:
      "Math Problem: The parking lot at a grocery store has 90 cars in it (30% of the cars are two-toned). How many cars are two-toned? After 5 hours, the 2 cars are 2,750.5 km apart. Find the speed of each car? Tip! The second car was driven by Sgt. Grant's son.",
    tokens: [
      {index: 0, value: 'Math', break: ' '},
      {index: 5, value: 'Problem', break: ':'},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'The', break: ' '},
      {index: 18, value: 'parking', break: ' '},
      {index: 26, value: 'lot', break: ' '},
      {index: 30, value: 'at', break: ' '},
      {index: 33, value: 'a', break: ' '},
      {index: 35, value: 'grocery', break: ' '},
      {index: 43, value: 'store', break: ' '},
      {index: 49, value: 'has', break: ' '},
      {index: 53, value: '90', break: ' '},
      {index: 56, value: 'cars', break: ' '},
      {index: 61, value: 'in', break: ' '},
      {index: 64, value: 'it', break: ' '},
      {index: 67, value: '', break: '('},
      {index: 68, value: '30', break: '%'},
      {index: 71, value: '', break: ' '},
      {index: 72, value: 'of', break: ' '},
      {index: 75, value: 'the', break: ' '},
      {index: 79, value: 'cars', break: ' '},
      {index: 84, value: 'are', break: ' '},
      {index: 88, value: 'two', break: '-'},
      {index: 92, value: 'toned', break: ')'},
      {index: 98, value: '', break: '.'},
      {index: 99, value: '', break: ' '},
      {index: 100, value: 'How', break: ' '},
      {index: 104, value: 'many', break: ' '},
      {index: 109, value: 'cars', break: ' '},
      {index: 114, value: 'are', break: ' '},
      {index: 118, value: 'two', break: '-'},
      {index: 122, value: 'toned', break: '?'},
      {index: 128, value: '', break: ' '},
      {index: 129, value: 'After', break: ' '},
      {index: 135, value: '5', break: ' '},
      {index: 137, value: 'hours', break: ','},
      {index: 143, value: '', break: ' '},
      {index: 144, value: 'the', break: ' '},
      {index: 148, value: '2', break: ' '},
      {index: 150, value: 'cars', break: ' '},
      {index: 155, value: 'are', break: ' '},
      {index: 159, value: '2', break: ','},
      {index: 161, value: '750', break: '.'},
      {index: 165, value: '5', break: ' '},
      {index: 167, value: 'km', break: ' '},
      {index: 170, value: 'apart', break: '.'},
      {index: 176, value: '', break: ' '},
      {index: 177, value: 'Find', break: ' '},
      {index: 182, value: 'the', break: ' '},
      {index: 186, value: 'speed', break: ' '},
      {index: 192, value: 'of', break: ' '},
      {index: 195, value: 'each', break: ' '},
      {index: 200, value: 'car', break: '?'},
      {index: 204, value: '', break: ' '},
      {index: 205, value: 'Tip', break: '!'},
      {index: 209, value: '', break: ' '},
      {index: 210, value: 'The', break: ' '},
      {index: 214, value: 'second', break: ' '},
      {index: 221, value: 'car', break: ' '},
      {index: 225, value: 'was', break: ' '},
      {index: 229, value: 'driven', break: ' '},
      {index: 236, value: 'by', break: ' '},
      {index: 239, value: 'Sgt', break: '.'},
      {index: 243, value: '', break: ' '},
      {index: 244, value: 'Grant', break: "'"},
      {index: 250, value: 's', break: ' '},
      {index: 252, value: 'son', break: '.'},
    ],
  },
  {
    scenario: 'english',
    source: `She saw Sharif's shoes on the sofa. But was she so sure those were Sharif's shoes she saw?`,
    tokens: [
      {index: 0, value: 'She', break: ' '},
      {index: 4, value: 'saw', break: ' '},
      {index: 8, value: 'Sharif', break: "'"},
      {index: 15, value: 's', break: ' '},
      {index: 17, value: 'shoes', break: ' '},
      {index: 23, value: 'on', break: ' '},
      {index: 26, value: 'the', break: ' '},
      {index: 30, value: 'sofa', break: '.'},
      {index: 35, value: '', break: ' '},
      {index: 36, value: 'But', break: ' '},
      {index: 40, value: 'was', break: ' '},
      {index: 44, value: 'she', break: ' '},
      {index: 48, value: 'so', break: ' '},
      {index: 51, value: 'sure', break: ' '},
      {index: 56, value: 'those', break: ' '},
      {index: 62, value: 'were', break: ' '},
      {index: 67, value: 'Sharif', break: "'"},
      {index: 74, value: 's', break: ' '},
      {index: 76, value: 'shoes', break: ' '},
      {index: 82, value: 'she', break: ' '},
      {index: 86, value: 'saw', break: '?'},
    ],
  },
  {
    scenario: 'portuguese (brazil)',
    source:
      'O doce perguntou ao doce: “Qual é o doce mais doce?” O doce respondeu ao doce: “O doce de batata doce!”',
    tokens: [
      {index: 0, value: 'O', break: ' '},
      {index: 2, value: 'doce', break: ' '},
      {index: 7, value: 'perguntou', break: ' '},
      {index: 17, value: 'ao', break: ' '},
      {index: 20, value: 'doce', break: ':'},
      {index: 25, value: '', break: ' '},
      {index: 26, value: '', break: '“'},
      {index: 27, value: 'Qual', break: ' '},
      {index: 32, value: 'é', break: ' '},
      {index: 34, value: 'o', break: ' '},
      {index: 36, value: 'doce', break: ' '},
      {index: 41, value: 'mais', break: ' '},
      {index: 46, value: 'doce', break: '?'},
      {index: 51, value: '', break: '”'},
      {index: 52, value: '', break: ' '},
      {index: 53, value: 'O', break: ' '},
      {index: 55, value: 'doce', break: ' '},
      {index: 60, value: 'respondeu', break: ' '},
      {index: 70, value: 'ao', break: ' '},
      {index: 73, value: 'doce', break: ':'},
      {index: 78, value: '', break: ' '},
      {index: 79, value: '', break: '“'},
      {index: 80, value: 'O', break: ' '},
      {index: 82, value: 'doce', break: ' '},
      {index: 87, value: 'de', break: ' '},
      {index: 90, value: 'batata', break: ' '},
      {index: 97, value: 'doce', break: '!'},
      {index: 102, value: '', break: '”'},
    ],
  },
  {
    scenario: 'spanish',
    source: 'Pablito clavó un clavito. ¿Qué clavito clavó Pablito?',
    tokens: [
      {index: 0, value: 'Pablito', break: ' '},
      {index: 8, value: 'clavó', break: ' '},
      {index: 14, value: 'un', break: ' '},
      {index: 17, value: 'clavito', break: '.'},
      {index: 25, value: '', break: ' '},
      {index: 26, value: '', break: '¿'},
      {index: 27, value: 'Qué', break: ' '},
      {index: 31, value: 'clavito', break: ' '},
      {index: 39, value: 'clavó', break: ' '},
      {index: 45, value: 'Pablito', break: '?'},
    ],
  },
  {
    scenario: 'italian',
    source:
      'C’è il questore in questura a quest’ora? No il questore in questura a quest’ora non c’è se ci fosse il questore in questura a quest’ora le avrebbe già fatto la questura.',
    tokens: [
      {index: 0, value: 'C', break: '’'},
      {index: 2, value: 'è', break: ' '},
      {index: 5, value: 'il', break: ' '},
      {index: 8, value: 'questore', break: ' '},
      {index: 17, value: 'in', break: ' '},
      {index: 20, value: 'questura', break: ' '},
      {index: 29, value: 'a', break: ' '},
      {index: 31, value: 'quest', break: '’'},
      {index: 37, value: 'ora', break: '?'},
      {index: 41, value: '', break: ' '},
      {index: 42, value: 'No', break: ' '},
      {index: 45, value: 'il', break: ' '},
      {index: 48, value: 'questore', break: ' '},
      {index: 57, value: 'in', break: ' '},
      {index: 60, value: 'questura', break: ' '},
      {index: 69, value: 'a', break: ' '},
      {index: 71, value: 'quest', break: '’'},
      {index: 77, value: 'ora', break: ' '},
      {index: 81, value: 'non', break: ' '},
      {index: 85, value: 'c', break: '’'},
      {index: 87, value: 'è', break: ' '},
      {index: 90, value: 'se', break: ' '},
      {index: 93, value: 'ci', break: ' '},
      {index: 96, value: 'fosse', break: ' '},
      {index: 102, value: 'il', break: ' '},
      {index: 105, value: 'questore', break: ' '},
      {index: 114, value: 'in', break: ' '},
      {index: 117, value: 'questura', break: ' '},
      {index: 126, value: 'a', break: ' '},
      {index: 128, value: 'quest', break: '’'},
      {index: 134, value: 'ora', break: ' '},
      {index: 138, value: 'le', break: ' '},
      {index: 141, value: 'avrebbe', break: ' '},
      {index: 149, value: 'già', break: ' '},
      {index: 154, value: 'fatto', break: ' '},
      {index: 160, value: 'la', break: ' '},
      {index: 163, value: 'questura', break: '.'},
    ],
  },
  {
    scenario: 'french',
    source:
      'L’oie niche bas, la pie niche haut : où niche l’hibou ? L’hibou niche ni haut ni bas.',
    tokens: [
      {index: 0, value: 'L', break: '’'},
      {index: 2, value: 'oie', break: ' '},
      {index: 6, value: 'niche', break: ' '},
      {index: 12, value: 'bas', break: ','},
      {index: 16, value: '', break: ' '},
      {index: 17, value: 'la', break: ' '},
      {index: 20, value: 'pie', break: ' '},
      {index: 24, value: 'niche', break: ' '},
      {index: 30, value: 'haut', break: ' '},
      {index: 35, value: '', break: ':'},
      {index: 36, value: '', break: ' '},
      {index: 37, value: 'où', break: ' '},
      {index: 40, value: 'niche', break: ' '},
      {index: 46, value: 'l', break: '’'},
      {index: 48, value: 'hibou', break: ' '},
      {index: 54, value: '', break: '?'},
      {index: 55, value: '', break: ' '},
      {index: 56, value: 'L', break: '’'},
      {index: 58, value: 'hibou', break: ' '},
      {index: 64, value: 'niche', break: ' '},
      {index: 70, value: 'ni', break: ' '},
      {index: 73, value: 'haut', break: ' '},
      {index: 78, value: 'ni', break: ' '},
      {index: 81, value: 'bas', break: '.'},
    ],
  },
  {
    scenario: 'russian',
    source:
      'Ехал Грека через реку, видит Грека—в реке рак. Сунул Грека руку в реку. Рак за руку Греку цап!',
    tokens: [
      {index: 0, value: 'Ехал', break: ' '},
      {index: 5, value: 'Грека', break: ' '},
      {index: 11, value: 'через', break: ' '},
      {index: 17, value: 'реку', break: ','},
      {index: 22, value: '', break: ' '},
      {index: 23, value: 'видит', break: ' '},
      {index: 29, value: 'Грека', break: '—'},
      {index: 35, value: 'в', break: ' '},
      {index: 37, value: 'реке', break: ' '},
      {index: 42, value: 'рак', break: '.'},
      {index: 46, value: '', break: ' '},
      {index: 47, value: 'Сунул', break: ' '},
      {index: 53, value: 'Грека', break: ' '},
      {index: 59, value: 'руку', break: ' '},
      {index: 64, value: 'в', break: ' '},
      {index: 66, value: 'реку', break: '.'},
      {index: 71, value: '', break: ' '},
      {index: 72, value: 'Рак', break: ' '},
      {index: 76, value: 'за', break: ' '},
      {index: 79, value: 'руку', break: ' '},
      {index: 84, value: 'Греку', break: ' '},
      {index: 90, value: 'цап', break: '!'},
    ],
  },
  {
    scenario: 'portuguese (portugal)',
    source: 'Fui ao mar colher cordões, vim do mar cordões colhi.',
    tokens: [
      {index: 0, value: 'Fui', break: ' '},
      {index: 4, value: 'ao', break: ' '},
      {index: 7, value: 'mar', break: ' '},
      {index: 11, value: 'colher', break: ' '},
      {index: 18, value: 'cordões', break: ','},
      {index: 26, value: '', break: ' '},
      {index: 27, value: 'vim', break: ' '},
      {index: 31, value: 'do', break: ' '},
      {index: 34, value: 'mar', break: ' '},
      {index: 38, value: 'cordões', break: ' '},
      {index: 46, value: 'colhi', break: '.'},
    ],
  },
  {
    scenario: 'polish',
    source: 'Pójdźże, kiń tę chmurność w głąb flaszy',
    tokens: [
      {index: 0, value: 'Pójdźże', break: ','},
      {index: 8, value: '', break: ' '},
      {index: 9, value: 'kiń', break: ' '},
      {index: 13, value: 'tę', break: ' '},
      {index: 16, value: 'chmurność', break: ' '},
      {index: 26, value: 'w', break: ' '},
      {index: 28, value: 'głąb', break: ' '},
      {index: 33, value: 'flaszy', break: ''},
    ],
  },
  {
    scenario: 'german',
    source:
      'Ob er aber über Oberammergau oder ob er über Unterammergau oder ob er überhaupt nicht kommt, ist nicht gewiss.',
    tokens: [
      {index: 0, value: 'Ob', break: ' '},
      {index: 3, value: 'er', break: ' '},
      {index: 6, value: 'aber', break: ' '},
      {index: 11, value: 'über', break: ' '},
      {index: 16, value: 'Oberammergau', break: ' '},
      {index: 29, value: 'oder', break: ' '},
      {index: 34, value: 'ob', break: ' '},
      {index: 37, value: 'er', break: ' '},
      {index: 40, value: 'über', break: ' '},
      {index: 45, value: 'Unterammergau', break: ' '},
      {index: 59, value: 'oder', break: ' '},
      {index: 64, value: 'ob', break: ' '},
      {index: 67, value: 'er', break: ' '},
      {index: 70, value: 'überhaupt', break: ' '},
      {index: 80, value: 'nicht', break: ' '},
      {index: 86, value: 'kommt', break: ','},
      {index: 92, value: '', break: ' '},
      {index: 93, value: 'ist', break: ' '},
      {index: 97, value: 'nicht', break: ' '},
      {index: 103, value: 'gewiss', break: '.'},
    ],
  },
  {
    scenario: 'vietnamese',
    source: 'Cô cũng công con công như cốc cốc cốc',
    tokens: [
      {index: 0, value: 'Cô', break: ' '},
      {index: 3, value: 'cũng', break: ' '},
      {index: 8, value: 'công', break: ' '},
      {index: 13, value: 'con', break: ' '},
      {index: 17, value: 'công', break: ' '},
      {index: 22, value: 'như', break: ' '},
      {index: 26, value: 'cốc', break: ' '},
      {index: 30, value: 'cốc', break: ' '},
      {index: 34, value: 'cốc', break: ''},
    ],
  },
  {
    scenario: 'dutch',
    source: `Effe op 't Rijswijkseplein vijfenvijftig ijzeren schijthuispijpleidingen halen.`,
    tokens: [
      {index: 0, value: 'Effe', break: ' '},
      {index: 5, value: 'op', break: ' '},
      {index: 8, value: '', break: "'"},
      {index: 9, value: 't', break: ' '},
      {index: 11, value: 'Rijswijkseplein', break: ' '},
      {index: 27, value: 'vijfenvijftig', break: ' '},
      {index: 41, value: 'ijzeren', break: ' '},
      {index: 49, value: 'schijthuispijpleidingen', break: ' '},
      {index: 73, value: 'halen', break: '.'},
    ],
  },
  {
    scenario: 'turkish',
    source: 'Şu köşe yaz köşesi, şu köşe kış köşesi, ortadaki su şişesi.',
    tokens: [
      {index: 0, value: 'Şu', break: ' '},
      {index: 3, value: 'köşe', break: ' '},
      {index: 8, value: 'yaz', break: ' '},
      {index: 12, value: 'köşesi', break: ','},
      {index: 19, value: '', break: ' '},
      {index: 20, value: 'şu', break: ' '},
      {index: 23, value: 'köşe', break: ' '},
      {index: 28, value: 'kış', break: ' '},
      {index: 32, value: 'köşesi', break: ','},
      {index: 39, value: '', break: ' '},
      {index: 40, value: 'ortadaki', break: ' '},
      {index: 49, value: 'su', break: ' '},
      {index: 52, value: 'şişesi', break: '.'},
    ],
  },
  {
    scenario: 'ukrainian',
    source: 'Бурі бобри брід перебрели забули бобри забрати торби.',
    tokens: [
      {index: 0, value: 'Бурі', break: ' '},
      {index: 5, value: 'бобри', break: ' '},
      {index: 11, value: 'брід', break: ' '},
      {index: 16, value: 'перебрели', break: ' '},
      {index: 26, value: 'забули', break: ' '},
      {index: 33, value: 'бобри', break: ' '},
      {index: 39, value: 'забрати', break: ' '},
      {index: 47, value: 'торби', break: '.'},
    ],
  },
  {
    scenario: 'indonesian',
    source: 'Kucing kuningku, kencing di kunci-kunciku',
    tokens: [
      {index: 0, value: 'Kucing', break: ' '},
      {index: 7, value: 'kuningku', break: ','},
      {index: 16, value: '', break: ' '},
      {index: 17, value: 'kencing', break: ' '},
      {index: 25, value: 'di', break: ' '},
      {index: 28, value: 'kunci', break: '-'},
      {index: 34, value: 'kunciku', break: ''},
    ],
  },
  {
    scenario: 'danish',
    source: 'Fem flade flødeboller på et fladt flødebollefad.',
    tokens: [
      {index: 0, value: 'Fem', break: ' '},
      {index: 4, value: 'flade', break: ' '},
      {index: 10, value: 'flødeboller', break: ' '},
      {index: 22, value: 'på', break: ' '},
      {index: 25, value: 'et', break: ' '},
      {index: 28, value: 'fladt', break: ' '},
      {index: 34, value: 'flødebollefad', break: '.'},
    ],
  },
  {
    scenario: 'swedish',
    source:
      'Flyg, fula fluga, flyg, (över Ålands hav)! Och den fula flugan flög.',
    tokens: [
      {index: 0, value: 'Flyg', break: ','},
      {index: 5, value: '', break: ' '},
      {index: 6, value: 'fula', break: ' '},
      {index: 11, value: 'fluga', break: ','},
      {index: 17, value: '', break: ' '},
      {index: 18, value: 'flyg', break: ','},
      {index: 23, value: '', break: ' '},
      {index: 24, value: '', break: '('},
      {index: 25, value: 'över', break: ' '},
      {index: 30, value: 'Ålands', break: ' '},
      {index: 37, value: 'hav', break: ')'},
      {index: 41, value: '', break: '!'},
      {index: 42, value: '', break: ' '},
      {index: 43, value: 'Och', break: ' '},
      {index: 47, value: 'den', break: ' '},
      {index: 51, value: 'fula', break: ' '},
      {index: 56, value: 'flugan', break: ' '},
      {index: 63, value: 'flög', break: '.'},
    ],
  },
  {
    scenario: 'greek',
    source: `Άσπρη πέτρα ξέξασπρη κι απ' τον ήλιο ξεξασπρότερη.`,
    tokens: [
      {index: 0, value: 'Άσπρη', break: ' '},
      {index: 6, value: 'πέτρα', break: ' '},
      {index: 12, value: 'ξέξασπρη', break: ' '},
      {index: 21, value: 'κι', break: ' '},
      {index: 24, value: 'απ', break: "'"},
      {index: 27, value: '', break: ' '},
      {index: 28, value: 'τον', break: ' '},
      {index: 32, value: 'ήλιο', break: ' '},
      {index: 37, value: 'ξεξασπρότερη', break: '.'},
    ],
  },
  {
    scenario: 'hungarian',
    source: 'Mit sütsz, kis szűcs? Sós húst sütsz, kis szűcs?',
    tokens: [
      {index: 0, value: 'Mit', break: ' '},
      {index: 4, value: 'sütsz', break: ','},
      {index: 10, value: '', break: ' '},
      {index: 11, value: 'kis', break: ' '},
      {index: 15, value: 'szűcs', break: '?'},
      {index: 21, value: '', break: ' '},
      {index: 22, value: 'Sós', break: ' '},
      {index: 26, value: 'húst', break: ' '},
      {index: 31, value: 'sütsz', break: ','},
      {index: 37, value: '', break: ' '},
      {index: 38, value: 'kis', break: ' '},
      {index: 42, value: 'szűcs', break: '?'},
    ],
  },
  {
    scenario: 'czech',
    source: 'Pštros s pštrosicí a pštrosáčaty šli do pštrosačárny.',
    tokens: [
      {index: 0, value: 'Pštros', break: ' '},
      {index: 7, value: 's', break: ' '},
      {index: 9, value: 'pštrosicí', break: ' '},
      {index: 19, value: 'a', break: ' '},
      {index: 21, value: 'pštrosáčaty', break: ' '},
      {index: 33, value: 'šli', break: ' '},
      {index: 37, value: 'do', break: ' '},
      {index: 40, value: 'pštrosačárny', break: '.'},
    ],
  },
  {
    scenario: 'norwegian',
    source: 'En hælv kælv låg i ælva å fløt.',
    tokens: [
      {index: 0, value: 'En', break: ' '},
      {index: 3, value: 'hælv', break: ' '},
      {index: 8, value: 'kælv', break: ' '},
      {index: 13, value: 'låg', break: ' '},
      {index: 17, value: 'i', break: ' '},
      {index: 19, value: 'ælva', break: ' '},
      {index: 24, value: 'å', break: ' '},
      {index: 26, value: 'fløt', break: '.'},
    ],
  },
  {
    scenario: 'slovenian',
    source: 'Iz Ježce v Stožce čez cesto po rožce.',
    tokens: [
      {index: 0, value: 'Iz', break: ' '},
      {index: 3, value: 'Ježce', break: ' '},
      {index: 9, value: 'v', break: ' '},
      {index: 11, value: 'Stožce', break: ' '},
      {index: 18, value: 'čez', break: ' '},
      {index: 22, value: 'cesto', break: ' '},
      {index: 28, value: 'po', break: ' '},
      {index: 31, value: 'rožce', break: '.'},
    ],
  },
  {
    scenario: 'slovak',
    source: 'Päťtýždňové vĺčatá nervózne štekajú na môjho ďatľa v tŕní.',
    tokens: [
      {index: 0, value: 'Päťtýždňové', break: ' '},
      {index: 12, value: 'vĺčatá', break: ' '},
      {index: 19, value: 'nervózne', break: ' '},
      {index: 28, value: 'štekajú', break: ' '},
      {index: 36, value: 'na', break: ' '},
      {index: 39, value: 'môjho', break: ' '},
      {index: 45, value: 'ďatľa', break: ' '},
      {index: 51, value: 'v', break: ' '},
      {index: 53, value: 'tŕní', break: '.'},
    ],
  },
  {
    scenario: 'finnish',
    source: 'Ääliö, älä lyö! Ööliä läikkyy.',
    tokens: [
      {index: 0, value: 'Ääliö', break: ','},
      {index: 6, value: '', break: ' '},
      {index: 7, value: 'älä', break: ' '},
      {index: 11, value: 'lyö', break: '!'},
      {index: 15, value: '', break: ' '},
      {index: 16, value: 'Ööliä', break: ' '},
      {index: 22, value: 'läikkyy', break: '.'},
    ],
  },
  {
    scenario: 'croatian',
    source: 'Košulja Plava, Na Kojoj Piše ‘Kupi Me.',
    tokens: [
      {index: 0, value: 'Košulja', break: ' '},
      {index: 8, value: 'Plava', break: ','},
      {index: 14, value: '', break: ' '},
      {index: 15, value: 'Na', break: ' '},
      {index: 18, value: 'Kojoj', break: ' '},
      {index: 24, value: 'Piše', break: ' '},
      {index: 29, value: '', break: '‘'},
      {index: 30, value: 'Kupi', break: ' '},
      {index: 35, value: 'Me', break: '.'},
    ],
  },
  {
    scenario: 'catalan',
    source: `En Pinxo li va dir a en Panxo: vols que et punxi amb un punxó? I en Panxo li va dir a en Pinxo: punxa'm però a la panxa no.`,
    tokens: [
      {index: 0, value: 'En', break: ' '},
      {index: 3, value: 'Pinxo', break: ' '},
      {index: 9, value: 'li', break: ' '},
      {index: 12, value: 'va', break: ' '},
      {index: 15, value: 'dir', break: ' '},
      {index: 19, value: 'a', break: ' '},
      {index: 21, value: 'en', break: ' '},
      {index: 24, value: 'Panxo', break: ':'},
      {index: 30, value: '', break: ' '},
      {index: 31, value: 'vols', break: ' '},
      {index: 36, value: 'que', break: ' '},
      {index: 40, value: 'et', break: ' '},
      {index: 43, value: 'punxi', break: ' '},
      {index: 49, value: 'amb', break: ' '},
      {index: 53, value: 'un', break: ' '},
      {index: 56, value: 'punxó', break: '?'},
      {index: 62, value: '', break: ' '},
      {index: 63, value: 'I', break: ' '},
      {index: 65, value: 'en', break: ' '},
      {index: 68, value: 'Panxo', break: ' '},
      {index: 74, value: 'li', break: ' '},
      {index: 77, value: 'va', break: ' '},
      {index: 80, value: 'dir', break: ' '},
      {index: 84, value: 'a', break: ' '},
      {index: 86, value: 'en', break: ' '},
      {index: 89, value: 'Pinxo', break: ':'},
      {index: 95, value: '', break: ' '},
      {index: 96, value: 'punxa', break: "'"},
      {index: 102, value: 'm', break: ' '},
      {index: 104, value: 'però', break: ' '},
      {index: 109, value: 'a', break: ' '},
      {index: 111, value: 'la', break: ' '},
      {index: 114, value: 'panxa', break: ' '},
      {index: 120, value: 'no', break: '.'},
    ],
  },
  {
    scenario: 'romanian',
    source: 'Stanca stă-n castan ca Stan.',
    tokens: [
      {index: 0, value: 'Stanca', break: ' '},
      {index: 7, value: 'stă', break: '-'},
      {index: 11, value: 'n', break: ' '},
      {index: 13, value: 'castan', break: ' '},
      {index: 20, value: 'ca', break: ' '},
      {index: 23, value: 'Stan', break: '.'},
    ],
  },
  {
    scenario: 'estonian',
    source: 'Ööbikud hüürgavad Pääsküla jõe ääres pähklipuu põõsastes.',
    tokens: [
      {index: 0, value: 'Ööbikud', break: ' '},
      {index: 8, value: 'hüürgavad', break: ' '},
      {index: 18, value: 'Pääsküla', break: ' '},
      {index: 27, value: 'jõe', break: ' '},
      {index: 31, value: 'ääres', break: ' '},
      {index: 37, value: 'pähklipuu', break: ' '},
      {index: 47, value: 'põõsastes', break: '.'},
    ],
  },
  {
    scenario: 'bulgarian',
    source: 'Четири чучулига чачаха червен чай чрез чаша чучулига',
    tokens: [
      {index: 0, value: 'Четири', break: ' '},
      {index: 7, value: 'чучулига', break: ' '},
      {index: 16, value: 'чачаха', break: ' '},
      {index: 23, value: 'червен', break: ' '},
      {index: 30, value: 'чай', break: ' '},
      {index: 34, value: 'чрез', break: ' '},
      {index: 39, value: 'чаша', break: ' '},
      {index: 44, value: 'чучулига', break: ''},
    ],
  },
  {
    scenario: 'lithuanian',
    source: 'Šešios žąsys su šešiais žąsiukais.',
    tokens: [
      {index: 0, value: 'Šešios', break: ' '},
      {index: 7, value: 'žąsys', break: ' '},
      {index: 13, value: 'su', break: ' '},
      {index: 16, value: 'šešiais', break: ' '},
      {index: 24, value: 'žąsiukais', break: '.'},
    ],
  },
  {
    scenario: 'latvian',
    source: 'Dzīvē dzīvo dzīvu dzīvi! Dzīvam dzīvē dzīva dzīve.',
    tokens: [
      {index: 0, value: 'Dzīvē', break: ' '},
      {index: 6, value: 'dzīvo', break: ' '},
      {index: 12, value: 'dzīvu', break: ' '},
      {index: 18, value: 'dzīvi', break: '!'},
      {index: 24, value: '', break: ' '},
      {index: 25, value: 'Dzīvam', break: ' '},
      {index: 32, value: 'dzīvē', break: ' '},
      {index: 38, value: 'dzīva', break: ' '},
      {index: 44, value: 'dzīve', break: '.'},
    ],
  },
  {
    scenario: 'serbian',
    source: 'Najčvršći potrčko često trči čvrsto četvrtkom u Brčko.',
    tokens: [
      {index: 0, value: 'Najčvršći', break: ' '},
      {index: 10, value: 'potrčko', break: ' '},
      {index: 18, value: 'često', break: ' '},
      {index: 24, value: 'trči', break: ' '},
      {index: 29, value: 'čvrsto', break: ' '},
      {index: 36, value: 'četvrtkom', break: ' '},
      {index: 46, value: 'u', break: ' '},
      {index: 48, value: 'Brčko', break: '.'},
    ],
  },
  {
    scenario: 'persian',
    source: 'dâei châgh-e, châi dâgh-e',
    tokens: [
      {index: 0, value: 'dâei', break: ' '},
      {index: 5, value: 'châgh', break: '-'},
      {index: 11, value: 'e', break: ','},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'châi', break: ' '},
      {index: 19, value: 'dâgh', break: '-'},
      {index: 24, value: 'e', break: ''},
    ],
  },
] as const;
