// Weekly users by language
// https://docs.google.com/spreadsheets/d/1CGYlgdZq3x_Ti1n_l-m0Qc4BhsIoHv_AjjMhlbdxrZ4
// https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

export default [
  {
    scenario: 'Random',
    source: '.,!uidsog: !@foo $%^adg &*(asd)',
    tokens: [
      {index: 0, value: '', break: '.'},
      {index: 1, value: '', break: ','},
      {index: 2, value: '', break: '!'},
      {index: 3, value: 'uidsog', break: ':'},
      {index: 10, value: '', break: ' '},
      {index: 11, value: '', break: '!'},
      {index: 12, value: '', break: '@'},
      {index: 13, value: 'foo', break: ' '},
      {index: 17, value: '', break: '$'},
      {index: 18, value: '', break: '%'},
      {index: 19, value: '', break: '^'},
      {index: 20, value: 'adg', break: ' '},
      {index: 24, value: '', break: '&'},
      {index: 25, value: '', break: '*'},
      {index: 26, value: '', break: '('},
      {index: 27, value: 'asd', break: ')'},
    ],
    expected: {
      camelCase: 'uidsogFooAdgAsd',
      constantCase: 'UIDSOG_FOO_ADG_ASD',
      dotCase: 'uidsog.foo.adg.asd',
      lowerCase: '.,!uidsog: !@foo $%^adg &*(asd)',
      upperCase: '.,!UIDSOG: !@FOO $%^ADG &*(ASD)',
      noAccents: '.,!uidsog: !@foo $%^adg &*(asd)',
      paramCase: 'uidsog-foo-adg-asd',
      pascalCase: 'UidsogFooAdgAsd',
      snakeCase: 'uidsog_foo_adg_asd',
      toggleCase: '.,!UIDSOG: !@FOO $%^ADG &*(ASD)',
      sentenceCase: '.,!Uidsog: !@Foo $%^adg &*(asd)',
    },
  },
  {
    scenario: 'Numeric',
    source: '10 foo1 6h 2 30% 2,750.5 1/2',
    tokens: [
      {index: 0, value: '10', break: ' '},
      {index: 3, value: 'foo1', break: ' '},
      {index: 8, value: '6h', break: ' '},
      {index: 11, value: '2', break: ' '},
      {index: 13, value: '30', break: '%'},
      {index: 16, value: '', break: ' '},
      {index: 17, value: '2', break: ','},
      {index: 19, value: '750', break: '.'},
      {index: 23, value: '5', break: ' '},
      {index: 25, value: '1', break: '/'},
      {index: 27, value: '2', break: ''},
    ],
    expected: {
      camelCase: '10Foo1_6h_2_30_2_750_5_1_2',
      constantCase: '10_FOO1_6H_2_30_2_750_5_1_2',
      dotCase: '10.foo1.6h.2.30.2.750.5.1.2',
      lowerCase: '10 foo1 6h 2 30% 2,750.5 1/2',
      upperCase: '10 FOO1 6H 2 30% 2,750.5 1/2',
      noAccents: '10 foo1 6h 2 30% 2,750.5 1/2',
      paramCase: '10-foo1-6h-2-30-2-750-5-1-2',
      pascalCase: '10Foo1_6h_2_30_2_750_5_1_2',
      snakeCase: '10_foo1_6h_2_30_2_750_5_1_2',
      toggleCase: '10 FOO1 6H 2 30% 2,750.5 1/2',
      sentenceCase: '10 foo1 6h 2 30% 2,750.5 1/2',
    },
  },
  {
    scenario: 'Quotation Marks',
    source: `“My goodness” said ‘my’ father, "take off „your »dirty shoes« before” coming in the house."`,
    tokens: [
      {index: 0, value: '', break: '“'},
      {index: 1, value: 'My', break: ' '},
      {index: 4, value: 'goodness', break: '”'},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'said', break: ' '},
      {index: 19, value: '', break: '‘'},
      {index: 20, value: 'my', break: '’'},
      {index: 23, value: '', break: ' '},
      {index: 24, value: 'father', break: ','},
      {index: 31, value: '', break: ' '},
      {index: 32, value: '', break: '"'},
      {index: 33, value: 'take', break: ' '},
      {index: 38, value: 'off', break: ' '},
      {index: 42, value: '', break: '„'},
      {index: 43, value: 'your', break: ' '},
      {index: 48, value: '', break: '»'},
      {index: 49, value: 'dirty', break: ' '},
      {index: 55, value: 'shoes', break: '«'},
      {index: 61, value: '', break: ' '},
      {index: 62, value: 'before', break: '”'},
      {index: 69, value: '', break: ' '},
      {index: 70, value: 'coming', break: ' '},
      {index: 77, value: 'in', break: ' '},
      {index: 80, value: 'the', break: ' '},
      {index: 84, value: 'house', break: '.'},
      {index: 90, value: '', break: '"'},
    ],
    expected: {
      camelCase: 'myGoodnessSaidMyFatherTakeOffYourDirtyShoesBeforeComingInTheHouse',
      constantCase: 'MY_GOODNESS_SAID_MY_FATHER_TAKE_OFF_YOUR_DIRTY_SHOES_BEFORE_COMING_IN_THE_HOUSE',
      dotCase: 'my.goodness.said.my.father.take.off.your.dirty.shoes.before.coming.in.the.house',
      lowerCase: `“my goodness” said ‘my’ father, "take off „your »dirty shoes« before” coming in the house."`,
      upperCase: `“MY GOODNESS” SAID ‘MY’ FATHER, "TAKE OFF „YOUR »DIRTY SHOES« BEFORE” COMING IN THE HOUSE."`,
      noAccents: `“My goodness” said ‘my’ father, "take off „your »dirty shoes« before” coming in the house."`,
      paramCase: 'my-goodness-said-my-father-take-off-your-dirty-shoes-before-coming-in-the-house',
      pascalCase: 'MyGoodnessSaidMyFatherTakeOffYourDirtyShoesBeforeComingInTheHouse',
      snakeCase: 'my_goodness_said_my_father_take_off_your_dirty_shoes_before_coming_in_the_house',
      toggleCase: `“mY GOODNESS” SAID ‘MY’ FATHER, "TAKE OFF „YOUR »DIRTY SHOES« BEFORE” COMING IN THE HOUSE."`,
      sentenceCase: `“My goodness” said ‘My’ father, "Take off „Your »Dirty shoes« before” coming in the house."`,
    },
  },
  {
    scenario: 'Abbreviations',
    source: 'Contact Capt. O. J. Thompson during working hours i.e., between 9 a.m. and 5 p.m. on a weekday.',
    tokens: [
      {index: 0, value: 'Contact', break: ' '},
      {index: 8, value: 'Capt', break: '.'},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'O', break: '.'},
      {index: 16, value: '', break: ' '},
      {index: 17, value: 'J', break: '.'},
      {index: 19, value: '', break: ' '},
      {index: 20, value: 'Thompson', break: ' '},
      {index: 29, value: 'during', break: ' '},
      {index: 36, value: 'working', break: ' '},
      {index: 44, value: 'hours', break: ' '},
      {index: 50, value: 'i', break: '.'},
      {index: 52, value: 'e', break: '.'},
      {index: 54, value: '', break: ','},
      {index: 55, value: '', break: ' '},
      {index: 56, value: 'between', break: ' '},
      {index: 64, value: '9', break: ' '},
      {index: 66, value: 'a', break: '.'},
      {index: 68, value: 'm', break: '.'},
      {index: 70, value: '', break: ' '},
      {index: 71, value: 'and', break: ' '},
      {index: 75, value: '5', break: ' '},
      {index: 77, value: 'p', break: '.'},
      {index: 79, value: 'm', break: '.'},
      {index: 81, value: '', break: ' '},
      {index: 82, value: 'on', break: ' '},
      {index: 85, value: 'a', break: ' '},
      {index: 87, value: 'weekday', break: '.'},
    ],
    expected: {
      camelCase: 'contactCaptOJThompsonDuringWorkingHoursIEBetween_9AMAnd_5PMOnAWeekday',
      constantCase: 'CONTACT_CAPT_O_J_THOMPSON_DURING_WORKING_HOURS_I_E_BETWEEN_9_A_M_AND_5_P_M_ON_A_WEEKDAY',
      dotCase: 'contact.capt.o.j.thompson.during.working.hours.i.e.between.9.a.m.and.5.p.m.on.a.weekday',
      lowerCase: 'contact capt. o. j. thompson during working hours i.e., between 9 a.m. and 5 p.m. on a weekday.',
      upperCase: 'CONTACT CAPT. O. J. THOMPSON DURING WORKING HOURS I.E., BETWEEN 9 A.M. AND 5 P.M. ON A WEEKDAY.',
      noAccents: 'Contact Capt. O. J. Thompson during working hours i.e., between 9 a.m. and 5 p.m. on a weekday.',
      paramCase: 'contact-capt-o-j-thompson-during-working-hours-i-e-between-9-a-m-and-5-p-m-on-a-weekday',
      pascalCase: 'ContactCaptOJThompsonDuringWorkingHoursIEBetween_9AMAnd_5PMOnAWeekday',
      snakeCase: 'contact_capt_o_j_thompson_during_working_hours_i_e_between_9_a_m_and_5_p_m_on_a_weekday',
      toggleCase: 'cONTACT cAPT. o. j. tHOMPSON DURING WORKING HOURS I.E., BETWEEN 9 A.M. AND 5 P.M. ON A WEEKDAY.',
      sentenceCase: 'Contact capt. o. j. thompson during working hours i.e., between 9 a.m. and 5 p.m. on a weekday.',
    },
  },
  {
    scenario: 'Combined Diacritics',
    source: 'Ā́ Łōgī́ zǭ́ze c’è avrebbe già',
    tokens: [
      {index: 0, value: 'Ā́', break: ' '},
      {index: 4, value: 'Łōgī́', break: ' '},
      {index: 12, value: 'zǭ́ze', break: ' '},
      {index: 20, value: 'c', break: '’'},
      {index: 22, value: 'è', break: ' '},
      {index: 25, value: 'avrebbe', break: ' '},
      {index: 33, value: 'già', break: ''},
    ],
    expected: {
      camelCase: 'ā́Łōgī́Zǭ́zeCÈAvrebbeGià',
      constantCase: 'Ā́_ŁŌGĪ́_ZǬ́ZE_C_È_AVREBBE_GIÀ',
      dotCase: 'ā́.łōgī́.zǭ́ze.c.è.avrebbe.già',
      lowerCase: 'ā́ łōgī́ zǭ́ze c’è avrebbe già',
      upperCase: 'Ā́ ŁŌGĪ́ ZǬ́ZE C’È AVREBBE GIÀ',
      noAccents: 'A logi zoze c’e avrebbe gia',
      paramCase: 'ā́-łōgī́-zǭ́ze-c-è-avrebbe-già',
      pascalCase: 'Ā́Łōgī́Zǭ́zeCÈAvrebbeGià',
      snakeCase: 'ā́_łōgī́_zǭ́ze_c_è_avrebbe_già',
      toggleCase: 'ā́ łŌGĪ́ ZǬ́ZE C’È AVREBBE GIÀ',
      sentenceCase: 'Ā́ łōgī́ zǭ́ze c’è avrebbe già',
    },
  },
  {
    scenario: 'Many sentences',
    source: 'Hi! My name is, what? My name is, "Excuse me! Why?" who? My name is. Slim Shady.',
    tokens: [
      {index: 0, value: 'Hi', break: '!'},
      {index: 3, value: '', break: ' '},
      {index: 4, value: 'My', break: ' '},
      {index: 7, value: 'name', break: ' '},
      {index: 12, value: 'is', break: ','},
      {index: 15, value: '', break: ' '},
      {index: 16, value: 'what', break: '?'},
      {index: 21, value: '', break: ' '},
      {index: 22, value: 'My', break: ' '},
      {index: 25, value: 'name', break: ' '},
      {index: 30, value: 'is', break: ','},
      {index: 33, value: '', break: ' '},
      {index: 34, value: '', break: '"'},
      {index: 35, value: 'Excuse', break: ' '},
      {index: 42, value: 'me', break: '!'},
      {index: 45, value: '', break: ' '},
      {index: 46, value: 'Why', break: '?'},
      {index: 50, value: '', break: '"'},
      {index: 51, value: '', break: ' '},
      {index: 52, value: 'who', break: '?'},
      {index: 56, value: '', break: ' '},
      {index: 57, value: 'My', break: ' '},
      {index: 60, value: 'name', break: ' '},
      {index: 65, value: 'is', break: '.'},
      {index: 68, value: '', break: ' '},
      {index: 69, value: 'Slim', break: ' '},
      {index: 74, value: 'Shady', break: '.'},
    ],
    expected: {
      camelCase: 'hiMyNameIsWhatMyNameIsExcuseMeWhyWhoMyNameIsSlimShady',
      constantCase: 'HI_MY_NAME_IS_WHAT_MY_NAME_IS_EXCUSE_ME_WHY_WHO_MY_NAME_IS_SLIM_SHADY',
      dotCase: 'hi.my.name.is.what.my.name.is.excuse.me.why.who.my.name.is.slim.shady',
      lowerCase: 'hi! my name is, what? my name is, "excuse me! why?" who? my name is. slim shady.',
      upperCase: 'HI! MY NAME IS, WHAT? MY NAME IS, "EXCUSE ME! WHY?" WHO? MY NAME IS. SLIM SHADY.',
      noAccents: 'Hi! My name is, what? My name is, "Excuse me! Why?" who? My name is. Slim Shady.',
      paramCase: 'hi-my-name-is-what-my-name-is-excuse-me-why-who-my-name-is-slim-shady',
      pascalCase: 'HiMyNameIsWhatMyNameIsExcuseMeWhyWhoMyNameIsSlimShady',
      snakeCase: 'hi_my_name_is_what_my_name_is_excuse_me_why_who_my_name_is_slim_shady',
      toggleCase: 'hI! mY NAME IS, WHAT? mY NAME IS, "eXCUSE ME! wHY?" WHO? mY NAME IS. sLIM sHADY.',
      sentenceCase: 'Hi! My name is, what? My name is, "Excuse me! Why?" who? My name is. Slim shady.',
    },
  },
  {
    scenario: 'English',
    source: `She saw Sharif's shoes on the sofa. But was she so sure those were Sharif's shoes she saw?`,
    tokens: [
      {index: 0, value: 'She', break: ' '},
      {index: 4, value: 'saw', break: ' '},
      {index: 8, value: 'Sharif', break: "'"},
      {index: 15, value: 's', break: ' '},
      {index: 17, value: 'shoes', break: ' '},
      {index: 23, value: 'on', break: ' '},
      {index: 26, value: 'the', break: ' '},
      {index: 30, value: 'sofa', break: '.'},
      {index: 35, value: '', break: ' '},
      {index: 36, value: 'But', break: ' '},
      {index: 40, value: 'was', break: ' '},
      {index: 44, value: 'she', break: ' '},
      {index: 48, value: 'so', break: ' '},
      {index: 51, value: 'sure', break: ' '},
      {index: 56, value: 'those', break: ' '},
      {index: 62, value: 'were', break: ' '},
      {index: 67, value: 'Sharif', break: "'"},
      {index: 74, value: 's', break: ' '},
      {index: 76, value: 'shoes', break: ' '},
      {index: 82, value: 'she', break: ' '},
      {index: 86, value: 'saw', break: '?'},
    ],
    expected: {
      camelCase: 'sheSawSharifSShoesOnTheSofaButWasSheSoSureThoseWereSharifSShoesSheSaw',
      constantCase: 'SHE_SAW_SHARIF_S_SHOES_ON_THE_SOFA_BUT_WAS_SHE_SO_SURE_THOSE_WERE_SHARIF_S_SHOES_SHE_SAW',
      dotCase: 'she.saw.sharif.s.shoes.on.the.sofa.but.was.she.so.sure.those.were.sharif.s.shoes.she.saw',
      lowerCase: `she saw sharif's shoes on the sofa. but was she so sure those were sharif's shoes she saw?`,
      upperCase: `SHE SAW SHARIF'S SHOES ON THE SOFA. BUT WAS SHE SO SURE THOSE WERE SHARIF'S SHOES SHE SAW?`,
      noAccents: `She saw Sharif's shoes on the sofa. But was she so sure those were Sharif's shoes she saw?`,
      paramCase: 'she-saw-sharif-s-shoes-on-the-sofa-but-was-she-so-sure-those-were-sharif-s-shoes-she-saw',
      pascalCase: 'SheSawSharifSShoesOnTheSofaButWasSheSoSureThoseWereSharifSShoesSheSaw',
      snakeCase: 'she_saw_sharif_s_shoes_on_the_sofa_but_was_she_so_sure_those_were_sharif_s_shoes_she_saw',
      toggleCase: `sHE SAW sHARIF'S SHOES ON THE SOFA. bUT WAS SHE SO SURE THOSE WERE sHARIF'S SHOES SHE SAW?`,
      sentenceCase: `She saw sharif's shoes on the sofa. But was she so sure those were sharif's shoes she saw?`,
    },
  },
  {
    scenario: 'Portuguese (Brazil)',
    source: 'O doce perguntou ao doce: “Qual é o doce mais doce?” O doce respondeu ao doce: “O doce de batata doce!”',
    tokens: [
      {index: 0, value: 'O', break: ' '},
      {index: 2, value: 'doce', break: ' '},
      {index: 7, value: 'perguntou', break: ' '},
      {index: 17, value: 'ao', break: ' '},
      {index: 20, value: 'doce', break: ':'},
      {index: 25, value: '', break: ' '},
      {index: 26, value: '', break: '“'},
      {index: 27, value: 'Qual', break: ' '},
      {index: 32, value: 'é', break: ' '},
      {index: 34, value: 'o', break: ' '},
      {index: 36, value: 'doce', break: ' '},
      {index: 41, value: 'mais', break: ' '},
      {index: 46, value: 'doce', break: '?'},
      {index: 51, value: '', break: '”'},
      {index: 52, value: '', break: ' '},
      {index: 53, value: 'O', break: ' '},
      {index: 55, value: 'doce', break: ' '},
      {index: 60, value: 'respondeu', break: ' '},
      {index: 70, value: 'ao', break: ' '},
      {index: 73, value: 'doce', break: ':'},
      {index: 78, value: '', break: ' '},
      {index: 79, value: '', break: '“'},
      {index: 80, value: 'O', break: ' '},
      {index: 82, value: 'doce', break: ' '},
      {index: 87, value: 'de', break: ' '},
      {index: 90, value: 'batata', break: ' '},
      {index: 97, value: 'doce', break: '!'},
      {index: 102, value: '', break: '”'},
    ],
    expected: {
      camelCase: 'oDocePerguntouAoDoceQualÉODoceMaisDoceODoceRespondeuAoDoceODoceDeBatataDoce',
      constantCase: 'O_DOCE_PERGUNTOU_AO_DOCE_QUAL_É_O_DOCE_MAIS_DOCE_O_DOCE_RESPONDEU_AO_DOCE_O_DOCE_DE_BATATA_DOCE',
      dotCase: 'o.doce.perguntou.ao.doce.qual.é.o.doce.mais.doce.o.doce.respondeu.ao.doce.o.doce.de.batata.doce',
      lowerCase: 'o doce perguntou ao doce: “qual é o doce mais doce?” o doce respondeu ao doce: “o doce de batata doce!”',
      upperCase: 'O DOCE PERGUNTOU AO DOCE: “QUAL É O DOCE MAIS DOCE?” O DOCE RESPONDEU AO DOCE: “O DOCE DE BATATA DOCE!”',
      noAccents: 'O doce perguntou ao doce: “Qual e o doce mais doce?” O doce respondeu ao doce: “O doce de batata doce!”',
      paramCase: 'o-doce-perguntou-ao-doce-qual-é-o-doce-mais-doce-o-doce-respondeu-ao-doce-o-doce-de-batata-doce',
      pascalCase: 'ODocePerguntouAoDoceQualÉODoceMaisDoceODoceRespondeuAoDoceODoceDeBatataDoce',
      snakeCase: 'o_doce_perguntou_ao_doce_qual_é_o_doce_mais_doce_o_doce_respondeu_ao_doce_o_doce_de_batata_doce',
      toggleCase: 'o DOCE PERGUNTOU AO DOCE: “qUAL É O DOCE MAIS DOCE?” o DOCE RESPONDEU AO DOCE: “o DOCE DE BATATA DOCE!”',
      sentenceCase: 'O doce perguntou ao doce: “Qual é o doce mais doce?” o doce respondeu ao doce: “O doce de batata doce!”',
    },
  },
  {
    scenario: 'Spanish',
    source: 'Pablito clavó un clavito. ¿Qué clavito clavó Pablito?',
    tokens: [
      {index: 0, value: 'Pablito', break: ' '},
      {index: 8, value: 'clavó', break: ' '},
      {index: 14, value: 'un', break: ' '},
      {index: 17, value: 'clavito', break: '.'},
      {index: 25, value: '', break: ' '},
      {index: 26, value: '', break: '¿'},
      {index: 27, value: 'Qué', break: ' '},
      {index: 31, value: 'clavito', break: ' '},
      {index: 39, value: 'clavó', break: ' '},
      {index: 45, value: 'Pablito', break: '?'},
    ],
    expected: {
      camelCase: 'pablitoClavóUnClavitoQuéClavitoClavóPablito',
      constantCase: 'PABLITO_CLAVÓ_UN_CLAVITO_QUÉ_CLAVITO_CLAVÓ_PABLITO',
      dotCase: 'pablito.clavó.un.clavito.qué.clavito.clavó.pablito',
      lowerCase: 'pablito clavó un clavito. ¿qué clavito clavó pablito?',
      upperCase: 'PABLITO CLAVÓ UN CLAVITO. ¿QUÉ CLAVITO CLAVÓ PABLITO?',
      noAccents: 'Pablito clavo un clavito. ¿Que clavito clavo Pablito?',
      paramCase: 'pablito-clavó-un-clavito-qué-clavito-clavó-pablito',
      pascalCase: 'PablitoClavóUnClavitoQuéClavitoClavóPablito',
      snakeCase: 'pablito_clavó_un_clavito_qué_clavito_clavó_pablito',
      toggleCase: 'pABLITO CLAVÓ UN CLAVITO. ¿qUÉ CLAVITO CLAVÓ pABLITO?',
      sentenceCase: 'Pablito clavó un clavito. ¿Qué clavito clavó pablito?',
    },
  },
  {
    scenario: 'Italian',
    source: `S'oggi seren non è doman seren sarà, se non sarà seren si rasserenerà.`,
    tokens: [
      {index: 0, value: 'S', break: "'"},
      {index: 2, value: 'oggi', break: ' '},
      {index: 7, value: 'seren', break: ' '},
      {index: 13, value: 'non', break: ' '},
      {index: 17, value: 'è', break: ' '},
      {index: 19, value: 'doman', break: ' '},
      {index: 25, value: 'seren', break: ' '},
      {index: 31, value: 'sarà', break: ','},
      {index: 36, value: '', break: ' '},
      {index: 37, value: 'se', break: ' '},
      {index: 40, value: 'non', break: ' '},
      {index: 44, value: 'sarà', break: ' '},
      {index: 49, value: 'seren', break: ' '},
      {index: 55, value: 'si', break: ' '},
      {index: 58, value: 'rasserenerà', break: '.'},
    ],
    expected: {
      camelCase: 'sOggiSerenNonÈDomanSerenSaràSeNonSaràSerenSiRasserenerà',
      constantCase: 'S_OGGI_SEREN_NON_È_DOMAN_SEREN_SARÀ_SE_NON_SARÀ_SEREN_SI_RASSERENERÀ',
      dotCase: 's.oggi.seren.non.è.doman.seren.sarà.se.non.sarà.seren.si.rasserenerà',
      lowerCase: `s'oggi seren non è doman seren sarà, se non sarà seren si rasserenerà.`,
      upperCase: `S'OGGI SEREN NON È DOMAN SEREN SARÀ, SE NON SARÀ SEREN SI RASSERENERÀ.`,
      noAccents: `S'oggi seren non e doman seren sara, se non sara seren si rasserenera.`,
      paramCase: 's-oggi-seren-non-è-doman-seren-sarà-se-non-sarà-seren-si-rasserenerà',
      pascalCase: 'SOggiSerenNonÈDomanSerenSaràSeNonSaràSerenSiRasserenerà',
      snakeCase: 's_oggi_seren_non_è_doman_seren_sarà_se_non_sarà_seren_si_rasserenerà',
      toggleCase: `s'OGGI SEREN NON È DOMAN SEREN SARÀ, SE NON SARÀ SEREN SI RASSERENERÀ.`,
      sentenceCase: `S'oggi seren non è doman seren sarà, se non sarà seren si rasserenerà.`,
    },
  },
  {
    scenario: 'French',
    source: 'L’oie niche bas, la pie niche haut : où niche l’hibou ? L’hibou niche ni haut ni bas.',
    tokens: [
      {index: 0, value: 'L', break: '’'},
      {index: 2, value: 'oie', break: ' '},
      {index: 6, value: 'niche', break: ' '},
      {index: 12, value: 'bas', break: ','},
      {index: 16, value: '', break: ' '},
      {index: 17, value: 'la', break: ' '},
      {index: 20, value: 'pie', break: ' '},
      {index: 24, value: 'niche', break: ' '},
      {index: 30, value: 'haut', break: ' '},
      {index: 35, value: '', break: ':'},
      {index: 36, value: '', break: ' '},
      {index: 37, value: 'où', break: ' '},
      {index: 40, value: 'niche', break: ' '},
      {index: 46, value: 'l', break: '’'},
      {index: 48, value: 'hibou', break: ' '},
      {index: 54, value: '', break: '?'},
      {index: 55, value: '', break: ' '},
      {index: 56, value: 'L', break: '’'},
      {index: 58, value: 'hibou', break: ' '},
      {index: 64, value: 'niche', break: ' '},
      {index: 70, value: 'ni', break: ' '},
      {index: 73, value: 'haut', break: ' '},
      {index: 78, value: 'ni', break: ' '},
      {index: 81, value: 'bas', break: '.'},
    ],
    expected: {
      camelCase: 'lOieNicheBasLaPieNicheHautOùNicheLHibouLHibouNicheNiHautNiBas',
      constantCase: 'L_OIE_NICHE_BAS_LA_PIE_NICHE_HAUT_OÙ_NICHE_L_HIBOU_L_HIBOU_NICHE_NI_HAUT_NI_BAS',
      dotCase: 'l.oie.niche.bas.la.pie.niche.haut.où.niche.l.hibou.l.hibou.niche.ni.haut.ni.bas',
      lowerCase: 'l’oie niche bas, la pie niche haut : où niche l’hibou ? l’hibou niche ni haut ni bas.',
      upperCase: 'L’OIE NICHE BAS, LA PIE NICHE HAUT : OÙ NICHE L’HIBOU ? L’HIBOU NICHE NI HAUT NI BAS.',
      noAccents: 'L’oie niche bas, la pie niche haut : ou niche l’hibou ? L’hibou niche ni haut ni bas.',
      paramCase: 'l-oie-niche-bas-la-pie-niche-haut-où-niche-l-hibou-l-hibou-niche-ni-haut-ni-bas',
      pascalCase: 'LOieNicheBasLaPieNicheHautOùNicheLHibouLHibouNicheNiHautNiBas',
      snakeCase: 'l_oie_niche_bas_la_pie_niche_haut_où_niche_l_hibou_l_hibou_niche_ni_haut_ni_bas',
      toggleCase: 'l’OIE NICHE BAS, LA PIE NICHE HAUT : OÙ NICHE L’HIBOU ? l’HIBOU NICHE NI HAUT NI BAS.',
      sentenceCase: 'L’oie niche bas, la pie niche haut : où niche l’hibou ? L’hibou niche ni haut ni bas.',
    },
  },
  {
    scenario: 'Russian',
    source: 'Ехал Грека через реку, видит Грека—в реке рак. Сунул Грека руку в реку. Рак за руку Греку цап!',
    tokens: [
      {index: 0, value: 'Ехал', break: ' '},
      {index: 5, value: 'Грека', break: ' '},
      {index: 11, value: 'через', break: ' '},
      {index: 17, value: 'реку', break: ','},
      {index: 22, value: '', break: ' '},
      {index: 23, value: 'видит', break: ' '},
      {index: 29, value: 'Грека', break: '—'},
      {index: 35, value: 'в', break: ' '},
      {index: 37, value: 'реке', break: ' '},
      {index: 42, value: 'рак', break: '.'},
      {index: 46, value: '', break: ' '},
      {index: 47, value: 'Сунул', break: ' '},
      {index: 53, value: 'Грека', break: ' '},
      {index: 59, value: 'руку', break: ' '},
      {index: 64, value: 'в', break: ' '},
      {index: 66, value: 'реку', break: '.'},
      {index: 71, value: '', break: ' '},
      {index: 72, value: 'Рак', break: ' '},
      {index: 76, value: 'за', break: ' '},
      {index: 79, value: 'руку', break: ' '},
      {index: 84, value: 'Греку', break: ' '},
      {index: 90, value: 'цап', break: '!'},
    ],
    expected: {
      camelCase: 'ехалГрекаЧерезРекуВидитГрекаВРекеРакСунулГрекаРукуВРекуРакЗаРукуГрекуЦап',
      constantCase: 'ЕХАЛ_ГРЕКА_ЧЕРЕЗ_РЕКУ_ВИДИТ_ГРЕКА_В_РЕКЕ_РАК_СУНУЛ_ГРЕКА_РУКУ_В_РЕКУ_РАК_ЗА_РУКУ_ГРЕКУ_ЦАП',
      dotCase: 'ехал.грека.через.реку.видит.грека.в.реке.рак.сунул.грека.руку.в.реку.рак.за.руку.греку.цап',
      lowerCase: 'ехал грека через реку, видит грека—в реке рак. сунул грека руку в реку. рак за руку греку цап!',
      upperCase: 'ЕХАЛ ГРЕКА ЧЕРЕЗ РЕКУ, ВИДИТ ГРЕКА—В РЕКЕ РАК. СУНУЛ ГРЕКА РУКУ В РЕКУ. РАК ЗА РУКУ ГРЕКУ ЦАП!',
      noAccents: 'Ехал Грека через реку, видит Грека—в реке рак. Сунул Грека руку в реку. Рак за руку Греку цап!',
      paramCase: 'ехал-грека-через-реку-видит-грека-в-реке-рак-сунул-грека-руку-в-реку-рак-за-руку-греку-цап',
      pascalCase: 'ЕхалГрекаЧерезРекуВидитГрекаВРекеРакСунулГрекаРукуВРекуРакЗаРукуГрекуЦап',
      snakeCase: 'ехал_грека_через_реку_видит_грека_в_реке_рак_сунул_грека_руку_в_реку_рак_за_руку_греку_цап',
      toggleCase: 'еХАЛ гРЕКА ЧЕРЕЗ РЕКУ, ВИДИТ гРЕКА—В РЕКЕ РАК. сУНУЛ гРЕКА РУКУ В РЕКУ. рАК ЗА РУКУ гРЕКУ ЦАП!',
      sentenceCase: 'Ехал грека через реку, видит грека—в реке рак. Сунул грека руку в реку. Рак за руку греку цап!',
    },
  },
  {
    scenario: 'Portuguese (Portugal)',
    source: 'Fui ao mar colher cordões, vim do mar cordões colhi.',
    tokens: [
      {index: 0, value: 'Fui', break: ' '},
      {index: 4, value: 'ao', break: ' '},
      {index: 7, value: 'mar', break: ' '},
      {index: 11, value: 'colher', break: ' '},
      {index: 18, value: 'cordões', break: ','},
      {index: 26, value: '', break: ' '},
      {index: 27, value: 'vim', break: ' '},
      {index: 31, value: 'do', break: ' '},
      {index: 34, value: 'mar', break: ' '},
      {index: 38, value: 'cordões', break: ' '},
      {index: 46, value: 'colhi', break: '.'},
    ],
    expected: {
      camelCase: 'fuiAoMarColherCordõesVimDoMarCordõesColhi',
      constantCase: 'FUI_AO_MAR_COLHER_CORDÕES_VIM_DO_MAR_CORDÕES_COLHI',
      dotCase: 'fui.ao.mar.colher.cordões.vim.do.mar.cordões.colhi',
      lowerCase: 'fui ao mar colher cordões, vim do mar cordões colhi.',
      upperCase: 'FUI AO MAR COLHER CORDÕES, VIM DO MAR CORDÕES COLHI.',
      noAccents: 'Fui ao mar colher cordoes, vim do mar cordoes colhi.',
      paramCase: 'fui-ao-mar-colher-cordões-vim-do-mar-cordões-colhi',
      pascalCase: 'FuiAoMarColherCordõesVimDoMarCordõesColhi',
      snakeCase: 'fui_ao_mar_colher_cordões_vim_do_mar_cordões_colhi',
      toggleCase: 'fUI AO MAR COLHER CORDÕES, VIM DO MAR CORDÕES COLHI.',
      sentenceCase: 'Fui ao mar colher cordões, vim do mar cordões colhi.',
    },
  },
  {
    scenario: 'Polish',
    source: 'Pójdźże, kiń tę chmurność w głąb flaszy',
    tokens: [
      {index: 0, value: 'Pójdźże', break: ','},
      {index: 8, value: '', break: ' '},
      {index: 9, value: 'kiń', break: ' '},
      {index: 13, value: 'tę', break: ' '},
      {index: 16, value: 'chmurność', break: ' '},
      {index: 26, value: 'w', break: ' '},
      {index: 28, value: 'głąb', break: ' '},
      {index: 33, value: 'flaszy', break: ''},
    ],
    expected: {
      camelCase: 'pójdźżeKińTęChmurnośćWGłąbFlaszy',
      constantCase: 'PÓJDŹŻE_KIŃ_TĘ_CHMURNOŚĆ_W_GŁĄB_FLASZY',
      dotCase: 'pójdźże.kiń.tę.chmurność.w.głąb.flaszy',
      lowerCase: 'pójdźże, kiń tę chmurność w głąb flaszy',
      upperCase: 'PÓJDŹŻE, KIŃ TĘ CHMURNOŚĆ W GŁĄB FLASZY',
      noAccents: 'Pojdzze, kin te chmurnosc w glab flaszy',
      paramCase: 'pójdźże-kiń-tę-chmurność-w-głąb-flaszy',
      pascalCase: 'PójdźżeKińTęChmurnośćWGłąbFlaszy',
      snakeCase: 'pójdźże_kiń_tę_chmurność_w_głąb_flaszy',
      toggleCase: 'pÓJDŹŻE, KIŃ TĘ CHMURNOŚĆ W GŁĄB FLASZY',
      sentenceCase: 'Pójdźże, kiń tę chmurność w głąb flaszy',
    },
  },
  {
    scenario: 'German',
    source: 'Ob er aber über Oberammergau oder ob er über Unterammergau oder ob er überhaupt nicht kommt, ist nicht gewiss.',
    tokens: [
      {index: 0, value: 'Ob', break: ' '},
      {index: 3, value: 'er', break: ' '},
      {index: 6, value: 'aber', break: ' '},
      {index: 11, value: 'über', break: ' '},
      {index: 16, value: 'Oberammergau', break: ' '},
      {index: 29, value: 'oder', break: ' '},
      {index: 34, value: 'ob', break: ' '},
      {index: 37, value: 'er', break: ' '},
      {index: 40, value: 'über', break: ' '},
      {index: 45, value: 'Unterammergau', break: ' '},
      {index: 59, value: 'oder', break: ' '},
      {index: 64, value: 'ob', break: ' '},
      {index: 67, value: 'er', break: ' '},
      {index: 70, value: 'überhaupt', break: ' '},
      {index: 80, value: 'nicht', break: ' '},
      {index: 86, value: 'kommt', break: ','},
      {index: 92, value: '', break: ' '},
      {index: 93, value: 'ist', break: ' '},
      {index: 97, value: 'nicht', break: ' '},
      {index: 103, value: 'gewiss', break: '.'},
    ],
    expected: {
      camelCase: 'obErAberÜberOberammergauOderObErÜberUnterammergauOderObErÜberhauptNichtKommtIstNichtGewiss',
      constantCase: 'OB_ER_ABER_ÜBER_OBERAMMERGAU_ODER_OB_ER_ÜBER_UNTERAMMERGAU_ODER_OB_ER_ÜBERHAUPT_NICHT_KOMMT_IST_NICHT_GEWISS',
      dotCase: 'ob.er.aber.über.oberammergau.oder.ob.er.über.unterammergau.oder.ob.er.überhaupt.nicht.kommt.ist.nicht.gewiss',
      lowerCase: 'ob er aber über oberammergau oder ob er über unterammergau oder ob er überhaupt nicht kommt, ist nicht gewiss.',
      upperCase: 'OB ER ABER ÜBER OBERAMMERGAU ODER OB ER ÜBER UNTERAMMERGAU ODER OB ER ÜBERHAUPT NICHT KOMMT, IST NICHT GEWISS.',
      noAccents: 'Ob er aber uber Oberammergau oder ob er uber Unterammergau oder ob er uberhaupt nicht kommt, ist nicht gewiss.',
      paramCase: 'ob-er-aber-über-oberammergau-oder-ob-er-über-unterammergau-oder-ob-er-überhaupt-nicht-kommt-ist-nicht-gewiss',
      pascalCase: 'ObErAberÜberOberammergauOderObErÜberUnterammergauOderObErÜberhauptNichtKommtIstNichtGewiss',
      snakeCase: 'ob_er_aber_über_oberammergau_oder_ob_er_über_unterammergau_oder_ob_er_überhaupt_nicht_kommt_ist_nicht_gewiss',
      toggleCase: 'oB ER ABER ÜBER oBERAMMERGAU ODER OB ER ÜBER uNTERAMMERGAU ODER OB ER ÜBERHAUPT NICHT KOMMT, IST NICHT GEWISS.',
      sentenceCase: 'Ob er aber über oberammergau oder ob er über unterammergau oder ob er überhaupt nicht kommt, ist nicht gewiss.',
    },
  },
  {
    scenario: 'Vietnamese',
    source: 'Cô cũng công con công như cốc cốc cốc',
    tokens: [
      {index: 0, value: 'Cô', break: ' '},
      {index: 3, value: 'cũng', break: ' '},
      {index: 8, value: 'công', break: ' '},
      {index: 13, value: 'con', break: ' '},
      {index: 17, value: 'công', break: ' '},
      {index: 22, value: 'như', break: ' '},
      {index: 26, value: 'cốc', break: ' '},
      {index: 30, value: 'cốc', break: ' '},
      {index: 34, value: 'cốc', break: ''},
    ],
    expected: {
      camelCase: 'côCũngCôngConCôngNhưCốcCốcCốc',
      constantCase: 'CÔ_CŨNG_CÔNG_CON_CÔNG_NHƯ_CỐC_CỐC_CỐC',
      dotCase: 'cô.cũng.công.con.công.như.cốc.cốc.cốc',
      lowerCase: 'cô cũng công con công như cốc cốc cốc',
      upperCase: 'CÔ CŨNG CÔNG CON CÔNG NHƯ CỐC CỐC CỐC',
      noAccents: 'Co cung cong con cong nhu coc coc coc',
      paramCase: 'cô-cũng-công-con-công-như-cốc-cốc-cốc',
      pascalCase: 'CôCũngCôngConCôngNhưCốcCốcCốc',
      snakeCase: 'cô_cũng_công_con_công_như_cốc_cốc_cốc',
      toggleCase: 'cÔ CŨNG CÔNG CON CÔNG NHƯ CỐC CỐC CỐC',
      sentenceCase: 'Cô cũng công con công như cốc cốc cốc',
    },
  },
  {
    scenario: 'Dutch',
    source: `Effe op 't Rijswijkseplein vijfenvijftig ijzeren schijthuispijpleidingen halen.`,
    tokens: [
      {index: 0, value: 'Effe', break: ' '},
      {index: 5, value: 'op', break: ' '},
      {index: 8, value: '', break: "'"},
      {index: 9, value: 't', break: ' '},
      {index: 11, value: 'Rijswijkseplein', break: ' '},
      {index: 27, value: 'vijfenvijftig', break: ' '},
      {index: 41, value: 'ijzeren', break: ' '},
      {index: 49, value: 'schijthuispijpleidingen', break: ' '},
      {index: 73, value: 'halen', break: '.'},
    ],
    expected: {
      camelCase: 'effeOpTRijswijksepleinVijfenvijftigIjzerenSchijthuispijpleidingenHalen',
      constantCase: 'EFFE_OP_T_RIJSWIJKSEPLEIN_VIJFENVIJFTIG_IJZEREN_SCHIJTHUISPIJPLEIDINGEN_HALEN',
      dotCase: 'effe.op.t.rijswijkseplein.vijfenvijftig.ijzeren.schijthuispijpleidingen.halen',
      lowerCase: `effe op 't rijswijkseplein vijfenvijftig ijzeren schijthuispijpleidingen halen.`,
      upperCase: `EFFE OP 'T RIJSWIJKSEPLEIN VIJFENVIJFTIG IJZEREN SCHIJTHUISPIJPLEIDINGEN HALEN.`,
      noAccents: `Effe op 't Rijswijkseplein vijfenvijftig ijzeren schijthuispijpleidingen halen.`,
      paramCase: 'effe-op-t-rijswijkseplein-vijfenvijftig-ijzeren-schijthuispijpleidingen-halen',
      pascalCase: 'EffeOpTRijswijksepleinVijfenvijftigIjzerenSchijthuispijpleidingenHalen',
      snakeCase: 'effe_op_t_rijswijkseplein_vijfenvijftig_ijzeren_schijthuispijpleidingen_halen',
      toggleCase: `eFFE OP 'T rIJSWIJKSEPLEIN VIJFENVIJFTIG IJZEREN SCHIJTHUISPIJPLEIDINGEN HALEN.`,
      sentenceCase: `Effe op 't rijswijkseplein vijfenvijftig ijzeren schijthuispijpleidingen halen.`,
    },
  },
  {
    scenario: 'Turkish',
    source: 'Şu köşe yaz köşesi, şu köşe kış köşesi, ortadaki su şişesi.',
    tokens: [
      {index: 0, value: 'Şu', break: ' '},
      {index: 3, value: 'köşe', break: ' '},
      {index: 8, value: 'yaz', break: ' '},
      {index: 12, value: 'köşesi', break: ','},
      {index: 19, value: '', break: ' '},
      {index: 20, value: 'şu', break: ' '},
      {index: 23, value: 'köşe', break: ' '},
      {index: 28, value: 'kış', break: ' '},
      {index: 32, value: 'köşesi', break: ','},
      {index: 39, value: '', break: ' '},
      {index: 40, value: 'ortadaki', break: ' '},
      {index: 49, value: 'su', break: ' '},
      {index: 52, value: 'şişesi', break: '.'},
    ],
    expected: {
      camelCase: 'şuKöşeYazKöşesiŞuKöşeKışKöşesiOrtadakiSuŞişesi',
      constantCase: 'ŞU_KÖŞE_YAZ_KÖŞESI_ŞU_KÖŞE_KIŞ_KÖŞESI_ORTADAKI_SU_ŞIŞESI',
      dotCase: 'şu.köşe.yaz.köşesi.şu.köşe.kış.köşesi.ortadaki.su.şişesi',
      lowerCase: 'şu köşe yaz köşesi, şu köşe kış köşesi, ortadaki su şişesi.',
      upperCase: 'ŞU KÖŞE YAZ KÖŞESI, ŞU KÖŞE KIŞ KÖŞESI, ORTADAKI SU ŞIŞESI.',
      noAccents: 'Su kose yaz kosesi, su kose kis kosesi, ortadaki su sisesi.',
      paramCase: 'şu-köşe-yaz-köşesi-şu-köşe-kış-köşesi-ortadaki-su-şişesi',
      pascalCase: 'ŞuKöşeYazKöşesiŞuKöşeKışKöşesiOrtadakiSuŞişesi',
      snakeCase: 'şu_köşe_yaz_köşesi_şu_köşe_kış_köşesi_ortadaki_su_şişesi',
      toggleCase: 'şU KÖŞE YAZ KÖŞESI, ŞU KÖŞE KIŞ KÖŞESI, ORTADAKI SU ŞIŞESI.',
      sentenceCase: 'Şu köşe yaz köşesi, şu köşe kış köşesi, ortadaki su şişesi.',
    },
  },
  {
    scenario: 'Ukrainian',
    source: 'Бурі бобри брід перебрели забули бобри забрати торби.',
    tokens: [
      {index: 0, value: 'Бурі', break: ' '},
      {index: 5, value: 'бобри', break: ' '},
      {index: 11, value: 'брід', break: ' '},
      {index: 16, value: 'перебрели', break: ' '},
      {index: 26, value: 'забули', break: ' '},
      {index: 33, value: 'бобри', break: ' '},
      {index: 39, value: 'забрати', break: ' '},
      {index: 47, value: 'торби', break: '.'},
    ],
    expected: {
      camelCase: 'буріБобриБрідПеребрелиЗабулиБобриЗабратиТорби',
      constantCase: 'БУРІ_БОБРИ_БРІД_ПЕРЕБРЕЛИ_ЗАБУЛИ_БОБРИ_ЗАБРАТИ_ТОРБИ',
      dotCase: 'бурі.бобри.брід.перебрели.забули.бобри.забрати.торби',
      lowerCase: 'бурі бобри брід перебрели забули бобри забрати торби.',
      upperCase: 'БУРІ БОБРИ БРІД ПЕРЕБРЕЛИ ЗАБУЛИ БОБРИ ЗАБРАТИ ТОРБИ.',
      noAccents: 'Бурі бобри брід перебрели забули бобри забрати торби.',
      paramCase: 'бурі-бобри-брід-перебрели-забули-бобри-забрати-торби',
      pascalCase: 'БуріБобриБрідПеребрелиЗабулиБобриЗабратиТорби',
      snakeCase: 'бурі_бобри_брід_перебрели_забули_бобри_забрати_торби',
      toggleCase: 'бУРІ БОБРИ БРІД ПЕРЕБРЕЛИ ЗАБУЛИ БОБРИ ЗАБРАТИ ТОРБИ.',
      sentenceCase: 'Бурі бобри брід перебрели забули бобри забрати торби.',
    },
  },
  {
    scenario: 'Indonesian',
    source: 'Kucing kuningku, kencing di kunci-kunciku',
    tokens: [
      {index: 0, value: 'Kucing', break: ' '},
      {index: 7, value: 'kuningku', break: ','},
      {index: 16, value: '', break: ' '},
      {index: 17, value: 'kencing', break: ' '},
      {index: 25, value: 'di', break: ' '},
      {index: 28, value: 'kunci', break: '-'},
      {index: 34, value: 'kunciku', break: ''},
    ],
    expected: {
      camelCase: 'kucingKuningkuKencingDiKunciKunciku',
      constantCase: 'KUCING_KUNINGKU_KENCING_DI_KUNCI_KUNCIKU',
      dotCase: 'kucing.kuningku.kencing.di.kunci.kunciku',
      lowerCase: 'kucing kuningku, kencing di kunci-kunciku',
      upperCase: 'KUCING KUNINGKU, KENCING DI KUNCI-KUNCIKU',
      noAccents: 'Kucing kuningku, kencing di kunci-kunciku',
      paramCase: 'kucing-kuningku-kencing-di-kunci-kunciku',
      pascalCase: 'KucingKuningkuKencingDiKunciKunciku',
      snakeCase: 'kucing_kuningku_kencing_di_kunci_kunciku',
      toggleCase: 'kUCING KUNINGKU, KENCING DI KUNCI-KUNCIKU',
      sentenceCase: 'Kucing kuningku, kencing di kunci-kunciku',
    },
  },
  {
    scenario: 'Danish',
    source: 'Fem flade flødeboller på et fladt flødebollefad.',
    tokens: [
      {index: 0, value: 'Fem', break: ' '},
      {index: 4, value: 'flade', break: ' '},
      {index: 10, value: 'flødeboller', break: ' '},
      {index: 22, value: 'på', break: ' '},
      {index: 25, value: 'et', break: ' '},
      {index: 28, value: 'fladt', break: ' '},
      {index: 34, value: 'flødebollefad', break: '.'},
    ],
    expected: {
      camelCase: 'femFladeFlødebollerPåEtFladtFlødebollefad',
      constantCase: 'FEM_FLADE_FLØDEBOLLER_PÅ_ET_FLADT_FLØDEBOLLEFAD',
      dotCase: 'fem.flade.flødeboller.på.et.fladt.flødebollefad',
      lowerCase: 'fem flade flødeboller på et fladt flødebollefad.',
      upperCase: 'FEM FLADE FLØDEBOLLER PÅ ET FLADT FLØDEBOLLEFAD.',
      noAccents: 'Fem flade flodeboller pa et fladt flodebollefad.',
      paramCase: 'fem-flade-flødeboller-på-et-fladt-flødebollefad',
      pascalCase: 'FemFladeFlødebollerPåEtFladtFlødebollefad',
      snakeCase: 'fem_flade_flødeboller_på_et_fladt_flødebollefad',
      toggleCase: 'fEM FLADE FLØDEBOLLER PÅ ET FLADT FLØDEBOLLEFAD.',
      sentenceCase: 'Fem flade flødeboller på et fladt flødebollefad.',
    },
  },
  {
    scenario: 'Swedish',
    source: 'Flyg, fula fluga, flyg, (över Ålands hav)! Och den fula flugan flög.',
    tokens: [
      {index: 0, value: 'Flyg', break: ','},
      {index: 5, value: '', break: ' '},
      {index: 6, value: 'fula', break: ' '},
      {index: 11, value: 'fluga', break: ','},
      {index: 17, value: '', break: ' '},
      {index: 18, value: 'flyg', break: ','},
      {index: 23, value: '', break: ' '},
      {index: 24, value: '', break: '('},
      {index: 25, value: 'över', break: ' '},
      {index: 30, value: 'Ålands', break: ' '},
      {index: 37, value: 'hav', break: ')'},
      {index: 41, value: '', break: '!'},
      {index: 42, value: '', break: ' '},
      {index: 43, value: 'Och', break: ' '},
      {index: 47, value: 'den', break: ' '},
      {index: 51, value: 'fula', break: ' '},
      {index: 56, value: 'flugan', break: ' '},
      {index: 63, value: 'flög', break: '.'},
    ],
    expected: {
      camelCase: 'flygFulaFlugaFlygÖverÅlandsHavOchDenFulaFluganFlög',
      constantCase: 'FLYG_FULA_FLUGA_FLYG_ÖVER_ÅLANDS_HAV_OCH_DEN_FULA_FLUGAN_FLÖG',
      dotCase: 'flyg.fula.fluga.flyg.över.ålands.hav.och.den.fula.flugan.flög',
      lowerCase: 'flyg, fula fluga, flyg, (över ålands hav)! och den fula flugan flög.',
      upperCase: 'FLYG, FULA FLUGA, FLYG, (ÖVER ÅLANDS HAV)! OCH DEN FULA FLUGAN FLÖG.',
      noAccents: 'Flyg, fula fluga, flyg, (over Alands hav)! Och den fula flugan flog.',
      paramCase: 'flyg-fula-fluga-flyg-över-ålands-hav-och-den-fula-flugan-flög',
      pascalCase: 'FlygFulaFlugaFlygÖverÅlandsHavOchDenFulaFluganFlög',
      snakeCase: 'flyg_fula_fluga_flyg_över_ålands_hav_och_den_fula_flugan_flög',
      toggleCase: 'fLYG, FULA FLUGA, FLYG, (ÖVER åLANDS HAV)! oCH DEN FULA FLUGAN FLÖG.',
      sentenceCase: 'Flyg, fula fluga, flyg, (över ålands hav)! Och den fula flugan flög.',
    },
  },
  {
    scenario: 'Greek',
    source: `Άσπρη πέτρα ξέξασπρη κι απ' τον ήλιο ξεξασπρότερη.`,
    tokens: [
      {index: 0, value: 'Άσπρη', break: ' '},
      {index: 6, value: 'πέτρα', break: ' '},
      {index: 12, value: 'ξέξασπρη', break: ' '},
      {index: 21, value: 'κι', break: ' '},
      {index: 24, value: 'απ', break: "'"},
      {index: 27, value: '', break: ' '},
      {index: 28, value: 'τον', break: ' '},
      {index: 32, value: 'ήλιο', break: ' '},
      {index: 37, value: 'ξεξασπρότερη', break: '.'},
    ],
    expected: {
      camelCase: 'άσπρηΠέτραΞέξασπρηΚιΑπΤονΉλιοΞεξασπρότερη',
      constantCase: 'ΆΣΠΡΗ_ΠΈΤΡΑ_ΞΈΞΑΣΠΡΗ_ΚΙ_ΑΠ_ΤΟΝ_ΉΛΙΟ_ΞΕΞΑΣΠΡΌΤΕΡΗ',
      dotCase: 'άσπρη.πέτρα.ξέξασπρη.κι.απ.τον.ήλιο.ξεξασπρότερη',
      lowerCase: `άσπρη πέτρα ξέξασπρη κι απ' τον ήλιο ξεξασπρότερη.`,
      upperCase: `ΆΣΠΡΗ ΠΈΤΡΑ ΞΈΞΑΣΠΡΗ ΚΙ ΑΠ' ΤΟΝ ΉΛΙΟ ΞΕΞΑΣΠΡΌΤΕΡΗ.`,
      noAccents: `Ασπρη πετρα ξεξασπρη κι απ' τον ηλιο ξεξασπροτερη.`,
      paramCase: 'άσπρη-πέτρα-ξέξασπρη-κι-απ-τον-ήλιο-ξεξασπρότερη',
      pascalCase: 'ΆσπρηΠέτραΞέξασπρηΚιΑπΤονΉλιοΞεξασπρότερη',
      snakeCase: 'άσπρη_πέτρα_ξέξασπρη_κι_απ_τον_ήλιο_ξεξασπρότερη',
      toggleCase: `άΣΠΡΗ ΠΈΤΡΑ ΞΈΞΑΣΠΡΗ ΚΙ ΑΠ' ΤΟΝ ΉΛΙΟ ΞΕΞΑΣΠΡΌΤΕΡΗ.`,
      sentenceCase: `Άσπρη πέτρα ξέξασπρη κι απ' τον ήλιο ξεξασπρότερη.`,
    },
  },
  {
    scenario: 'Hungarian',
    source: 'Mit sütsz, kis szűcs? Sós húst sütsz, kis szűcs?',
    tokens: [
      {index: 0, value: 'Mit', break: ' '},
      {index: 4, value: 'sütsz', break: ','},
      {index: 10, value: '', break: ' '},
      {index: 11, value: 'kis', break: ' '},
      {index: 15, value: 'szűcs', break: '?'},
      {index: 21, value: '', break: ' '},
      {index: 22, value: 'Sós', break: ' '},
      {index: 26, value: 'húst', break: ' '},
      {index: 31, value: 'sütsz', break: ','},
      {index: 37, value: '', break: ' '},
      {index: 38, value: 'kis', break: ' '},
      {index: 42, value: 'szűcs', break: '?'},
    ],
    expected: {
      camelCase: 'mitSütszKisSzűcsSósHústSütszKisSzűcs',
      constantCase: 'MIT_SÜTSZ_KIS_SZŰCS_SÓS_HÚST_SÜTSZ_KIS_SZŰCS',
      dotCase: 'mit.sütsz.kis.szűcs.sós.húst.sütsz.kis.szűcs',
      lowerCase: 'mit sütsz, kis szűcs? sós húst sütsz, kis szűcs?',
      upperCase: 'MIT SÜTSZ, KIS SZŰCS? SÓS HÚST SÜTSZ, KIS SZŰCS?',
      noAccents: 'Mit sutsz, kis szucs? Sos hust sutsz, kis szucs?',
      paramCase: 'mit-sütsz-kis-szűcs-sós-húst-sütsz-kis-szűcs',
      pascalCase: 'MitSütszKisSzűcsSósHústSütszKisSzűcs',
      snakeCase: 'mit_sütsz_kis_szűcs_sós_húst_sütsz_kis_szűcs',
      toggleCase: 'mIT SÜTSZ, KIS SZŰCS? sÓS HÚST SÜTSZ, KIS SZŰCS?',
      sentenceCase: 'Mit sütsz, kis szűcs? Sós húst sütsz, kis szűcs?',
    },
  },
  {
    scenario: 'Czech',
    source: 'Pštros s pštrosicí a pštrosáčaty šli do pštrosačárny.',
    tokens: [
      {index: 0, value: 'Pštros', break: ' '},
      {index: 7, value: 's', break: ' '},
      {index: 9, value: 'pštrosicí', break: ' '},
      {index: 19, value: 'a', break: ' '},
      {index: 21, value: 'pštrosáčaty', break: ' '},
      {index: 33, value: 'šli', break: ' '},
      {index: 37, value: 'do', break: ' '},
      {index: 40, value: 'pštrosačárny', break: '.'},
    ],
    expected: {
      camelCase: 'pštrosSPštrosicíAPštrosáčatyŠliDoPštrosačárny',
      constantCase: 'PŠTROS_S_PŠTROSICÍ_A_PŠTROSÁČATY_ŠLI_DO_PŠTROSAČÁRNY',
      dotCase: 'pštros.s.pštrosicí.a.pštrosáčaty.šli.do.pštrosačárny',
      lowerCase: 'pštros s pštrosicí a pštrosáčaty šli do pštrosačárny.',
      upperCase: 'PŠTROS S PŠTROSICÍ A PŠTROSÁČATY ŠLI DO PŠTROSAČÁRNY.',
      noAccents: 'Pstros s pstrosici a pstrosacaty sli do pstrosacarny.',
      paramCase: 'pštros-s-pštrosicí-a-pštrosáčaty-šli-do-pštrosačárny',
      pascalCase: 'PštrosSPštrosicíAPštrosáčatyŠliDoPštrosačárny',
      snakeCase: 'pštros_s_pštrosicí_a_pštrosáčaty_šli_do_pštrosačárny',
      toggleCase: 'pŠTROS S PŠTROSICÍ A PŠTROSÁČATY ŠLI DO PŠTROSAČÁRNY.',
      sentenceCase: 'Pštros s pštrosicí a pštrosáčaty šli do pštrosačárny.',
    },
  },
  {
    scenario: 'Norwegian',
    source: 'En hælv kælv låg i ælva å fløt.',
    tokens: [
      {index: 0, value: 'En', break: ' '},
      {index: 3, value: 'hælv', break: ' '},
      {index: 8, value: 'kælv', break: ' '},
      {index: 13, value: 'låg', break: ' '},
      {index: 17, value: 'i', break: ' '},
      {index: 19, value: 'ælva', break: ' '},
      {index: 24, value: 'å', break: ' '},
      {index: 26, value: 'fløt', break: '.'},
    ],
    expected: {
      camelCase: 'enHælvKælvLågIÆlvaÅFløt',
      constantCase: 'EN_HÆLV_KÆLV_LÅG_I_ÆLVA_Å_FLØT',
      dotCase: 'en.hælv.kælv.låg.i.ælva.å.fløt',
      lowerCase: 'en hælv kælv låg i ælva å fløt.',
      upperCase: 'EN HÆLV KÆLV LÅG I ÆLVA Å FLØT.',
      noAccents: 'En haelv kaelv lag i aelva a flot.',
      paramCase: 'en-hælv-kælv-låg-i-ælva-å-fløt',
      pascalCase: 'EnHælvKælvLågIÆlvaÅFløt',
      snakeCase: 'en_hælv_kælv_låg_i_ælva_å_fløt',
      toggleCase: 'eN HÆLV KÆLV LÅG I ÆLVA Å FLØT.',
      sentenceCase: 'En hælv kælv låg i ælva å fløt.',
    },
  },
  {
    scenario: 'Slovenian',
    source: 'Iz Ježce v Stožce čez cesto po rožce.',
    tokens: [
      {index: 0, value: 'Iz', break: ' '},
      {index: 3, value: 'Ježce', break: ' '},
      {index: 9, value: 'v', break: ' '},
      {index: 11, value: 'Stožce', break: ' '},
      {index: 18, value: 'čez', break: ' '},
      {index: 22, value: 'cesto', break: ' '},
      {index: 28, value: 'po', break: ' '},
      {index: 31, value: 'rožce', break: '.'},
    ],
    expected: {
      camelCase: 'izJežceVStožceČezCestoPoRožce',
      constantCase: 'IZ_JEŽCE_V_STOŽCE_ČEZ_CESTO_PO_ROŽCE',
      dotCase: 'iz.ježce.v.stožce.čez.cesto.po.rožce',
      lowerCase: 'iz ježce v stožce čez cesto po rožce.',
      upperCase: 'IZ JEŽCE V STOŽCE ČEZ CESTO PO ROŽCE.',
      noAccents: 'Iz Jezce v Stozce cez cesto po rozce.',
      paramCase: 'iz-ježce-v-stožce-čez-cesto-po-rožce',
      pascalCase: 'IzJežceVStožceČezCestoPoRožce',
      snakeCase: 'iz_ježce_v_stožce_čez_cesto_po_rožce',
      toggleCase: 'iZ jEŽCE V sTOŽCE ČEZ CESTO PO ROŽCE.',
      sentenceCase: 'Iz ježce v stožce čez cesto po rožce.',
    },
  },
  {
    scenario: 'Slovak',
    source: 'Päťtýždňové vĺčatá nervózne štekajú na môjho ďatľa v tŕní.',
    tokens: [
      {index: 0, value: 'Päťtýždňové', break: ' '},
      {index: 12, value: 'vĺčatá', break: ' '},
      {index: 19, value: 'nervózne', break: ' '},
      {index: 28, value: 'štekajú', break: ' '},
      {index: 36, value: 'na', break: ' '},
      {index: 39, value: 'môjho', break: ' '},
      {index: 45, value: 'ďatľa', break: ' '},
      {index: 51, value: 'v', break: ' '},
      {index: 53, value: 'tŕní', break: '.'},
    ],
    expected: {
      camelCase: 'päťtýždňovéVĺčatáNervózneŠtekajúNaMôjhoĎatľaVTŕní',
      constantCase: 'PÄŤTÝŽDŇOVÉ_VĹČATÁ_NERVÓZNE_ŠTEKAJÚ_NA_MÔJHO_ĎATĽA_V_TŔNÍ',
      dotCase: 'päťtýždňové.vĺčatá.nervózne.štekajú.na.môjho.ďatľa.v.tŕní',
      lowerCase: 'päťtýždňové vĺčatá nervózne štekajú na môjho ďatľa v tŕní.',
      upperCase: 'PÄŤTÝŽDŇOVÉ VĹČATÁ NERVÓZNE ŠTEKAJÚ NA MÔJHO ĎATĽA V TŔNÍ.',
      noAccents: 'Pattyzdnove vlcata nervozne stekaju na mojho datla v trni.',
      paramCase: 'päťtýždňové-vĺčatá-nervózne-štekajú-na-môjho-ďatľa-v-tŕní',
      pascalCase: 'PäťtýždňovéVĺčatáNervózneŠtekajúNaMôjhoĎatľaVTŕní',
      snakeCase: 'päťtýždňové_vĺčatá_nervózne_štekajú_na_môjho_ďatľa_v_tŕní',
      toggleCase: 'pÄŤTÝŽDŇOVÉ VĹČATÁ NERVÓZNE ŠTEKAJÚ NA MÔJHO ĎATĽA V TŔNÍ.',
      sentenceCase: 'Päťtýždňové vĺčatá nervózne štekajú na môjho ďatľa v tŕní.',
    },
  },
  {
    scenario: 'Finnish',
    source: 'Ääliö, älä lyö! Ööliä läikkyy.',
    tokens: [
      {index: 0, value: 'Ääliö', break: ','},
      {index: 6, value: '', break: ' '},
      {index: 7, value: 'älä', break: ' '},
      {index: 11, value: 'lyö', break: '!'},
      {index: 15, value: '', break: ' '},
      {index: 16, value: 'Ööliä', break: ' '},
      {index: 22, value: 'läikkyy', break: '.'},
    ],
    expected: {
      camelCase: 'ääliöÄläLyöÖöliäLäikkyy',
      constantCase: 'ÄÄLIÖ_ÄLÄ_LYÖ_ÖÖLIÄ_LÄIKKYY',
      dotCase: 'ääliö.älä.lyö.ööliä.läikkyy',
      lowerCase: 'ääliö, älä lyö! ööliä läikkyy.',
      upperCase: 'ÄÄLIÖ, ÄLÄ LYÖ! ÖÖLIÄ LÄIKKYY.',
      noAccents: 'Aalio, ala lyo! Oolia laikkyy.',
      paramCase: 'ääliö-älä-lyö-ööliä-läikkyy',
      pascalCase: 'ÄäliöÄläLyöÖöliäLäikkyy',
      snakeCase: 'ääliö_älä_lyö_ööliä_läikkyy',
      toggleCase: 'äÄLIÖ, ÄLÄ LYÖ! öÖLIÄ LÄIKKYY.',
      sentenceCase: 'Ääliö, älä lyö! Ööliä läikkyy.',
    },
  },
  {
    scenario: 'Croatian',
    source: 'Košulja Plava, Na Kojoj Piše ‘Kupi Me.',
    tokens: [
      {index: 0, value: 'Košulja', break: ' '},
      {index: 8, value: 'Plava', break: ','},
      {index: 14, value: '', break: ' '},
      {index: 15, value: 'Na', break: ' '},
      {index: 18, value: 'Kojoj', break: ' '},
      {index: 24, value: 'Piše', break: ' '},
      {index: 29, value: '', break: '‘'},
      {index: 30, value: 'Kupi', break: ' '},
      {index: 35, value: 'Me', break: '.'},
    ],
    expected: {
      camelCase: 'košuljaPlavaNaKojojPišeKupiMe',
      constantCase: 'KOŠULJA_PLAVA_NA_KOJOJ_PIŠE_KUPI_ME',
      dotCase: 'košulja.plava.na.kojoj.piše.kupi.me',
      lowerCase: 'košulja plava, na kojoj piše ‘kupi me.',
      upperCase: 'KOŠULJA PLAVA, NA KOJOJ PIŠE ‘KUPI ME.',
      noAccents: 'Kosulja Plava, Na Kojoj Pise ‘Kupi Me.',
      paramCase: 'košulja-plava-na-kojoj-piše-kupi-me',
      pascalCase: 'KošuljaPlavaNaKojojPišeKupiMe',
      snakeCase: 'košulja_plava_na_kojoj_piše_kupi_me',
      toggleCase: 'kOŠULJA pLAVA, nA kOJOJ pIŠE ‘kUPI mE.',
      sentenceCase: 'Košulja plava, na kojoj piše ‘Kupi me.',
    },
  },
  {
    scenario: 'Catalan',
    source: `Duc pa sec al sac, m'assec on sóc, i el suco amb suc.`,
    tokens: [
      {index: 0, value: 'Duc', break: ' '},
      {index: 4, value: 'pa', break: ' '},
      {index: 7, value: 'sec', break: ' '},
      {index: 11, value: 'al', break: ' '},
      {index: 14, value: 'sac', break: ','},
      {index: 18, value: '', break: ' '},
      {index: 19, value: 'm', break: "'"},
      {index: 21, value: 'assec', break: ' '},
      {index: 27, value: 'on', break: ' '},
      {index: 30, value: 'sóc', break: ','},
      {index: 34, value: '', break: ' '},
      {index: 35, value: 'i', break: ' '},
      {index: 37, value: 'el', break: ' '},
      {index: 40, value: 'suco', break: ' '},
      {index: 45, value: 'amb', break: ' '},
      {index: 49, value: 'suc', break: '.'},
    ],
    expected: {
      camelCase: 'ducPaSecAlSacMAssecOnSócIElSucoAmbSuc',
      constantCase: 'DUC_PA_SEC_AL_SAC_M_ASSEC_ON_SÓC_I_EL_SUCO_AMB_SUC',
      dotCase: 'duc.pa.sec.al.sac.m.assec.on.sóc.i.el.suco.amb.suc',
      lowerCase: `duc pa sec al sac, m'assec on sóc, i el suco amb suc.`,
      upperCase: `DUC PA SEC AL SAC, M'ASSEC ON SÓC, I EL SUCO AMB SUC.`,
      noAccents: `Duc pa sec al sac, m'assec on soc, i el suco amb suc.`,
      paramCase: 'duc-pa-sec-al-sac-m-assec-on-sóc-i-el-suco-amb-suc',
      pascalCase: 'DucPaSecAlSacMAssecOnSócIElSucoAmbSuc',
      snakeCase: 'duc_pa_sec_al_sac_m_assec_on_sóc_i_el_suco_amb_suc',
      toggleCase: `dUC PA SEC AL SAC, M'ASSEC ON SÓC, I EL SUCO AMB SUC.`,
      sentenceCase: `Duc pa sec al sac, m'assec on sóc, i el suco amb suc.`,
    },
  },
  {
    scenario: 'Romanian',
    source: 'Stanca stă-n castan ca Stan.',
    tokens: [
      {index: 0, value: 'Stanca', break: ' '},
      {index: 7, value: 'stă', break: '-'},
      {index: 11, value: 'n', break: ' '},
      {index: 13, value: 'castan', break: ' '},
      {index: 20, value: 'ca', break: ' '},
      {index: 23, value: 'Stan', break: '.'},
    ],
    expected: {
      camelCase: 'stancaStăNCastanCaStan',
      constantCase: 'STANCA_STĂ_N_CASTAN_CA_STAN',
      dotCase: 'stanca.stă.n.castan.ca.stan',
      lowerCase: 'stanca stă-n castan ca stan.',
      upperCase: 'STANCA STĂ-N CASTAN CA STAN.',
      noAccents: 'Stanca sta-n castan ca Stan.',
      paramCase: 'stanca-stă-n-castan-ca-stan',
      pascalCase: 'StancaStăNCastanCaStan',
      snakeCase: 'stanca_stă_n_castan_ca_stan',
      toggleCase: 'sTANCA STĂ-N CASTAN CA sTAN.',
      sentenceCase: 'Stanca stă-n castan ca stan.',
    },
  },
  {
    scenario: 'Estonian',
    source: 'Ööbikud hüürgavad Pääsküla jõe ääres pähklipuu põõsastes.',
    tokens: [
      {index: 0, value: 'Ööbikud', break: ' '},
      {index: 8, value: 'hüürgavad', break: ' '},
      {index: 18, value: 'Pääsküla', break: ' '},
      {index: 27, value: 'jõe', break: ' '},
      {index: 31, value: 'ääres', break: ' '},
      {index: 37, value: 'pähklipuu', break: ' '},
      {index: 47, value: 'põõsastes', break: '.'},
    ],
    expected: {
      camelCase: 'ööbikudHüürgavadPääskülaJõeÄäresPähklipuuPõõsastes',
      constantCase: 'ÖÖBIKUD_HÜÜRGAVAD_PÄÄSKÜLA_JÕE_ÄÄRES_PÄHKLIPUU_PÕÕSASTES',
      dotCase: 'ööbikud.hüürgavad.pääsküla.jõe.ääres.pähklipuu.põõsastes',
      lowerCase: 'ööbikud hüürgavad pääsküla jõe ääres pähklipuu põõsastes.',
      upperCase: 'ÖÖBIKUD HÜÜRGAVAD PÄÄSKÜLA JÕE ÄÄRES PÄHKLIPUU PÕÕSASTES.',
      noAccents: 'Oobikud huurgavad Paaskula joe aares pahklipuu poosastes.',
      paramCase: 'ööbikud-hüürgavad-pääsküla-jõe-ääres-pähklipuu-põõsastes',
      pascalCase: 'ÖöbikudHüürgavadPääskülaJõeÄäresPähklipuuPõõsastes',
      snakeCase: 'ööbikud_hüürgavad_pääsküla_jõe_ääres_pähklipuu_põõsastes',
      toggleCase: 'öÖBIKUD HÜÜRGAVAD pÄÄSKÜLA JÕE ÄÄRES PÄHKLIPUU PÕÕSASTES.',
      sentenceCase: 'Ööbikud hüürgavad pääsküla jõe ääres pähklipuu põõsastes.',
    },
  },
  {
    scenario: 'Bulgarian',
    source: 'Четири чучулига чачаха червен чай чрез чаша чучулига',
    tokens: [
      {index: 0, value: 'Четири', break: ' '},
      {index: 7, value: 'чучулига', break: ' '},
      {index: 16, value: 'чачаха', break: ' '},
      {index: 23, value: 'червен', break: ' '},
      {index: 30, value: 'чай', break: ' '},
      {index: 34, value: 'чрез', break: ' '},
      {index: 39, value: 'чаша', break: ' '},
      {index: 44, value: 'чучулига', break: ''},
    ],
    expected: {
      camelCase: 'четириЧучулигаЧачахаЧервенЧайЧрезЧашаЧучулига',
      constantCase: 'ЧЕТИРИ_ЧУЧУЛИГА_ЧАЧАХА_ЧЕРВЕН_ЧАЙ_ЧРЕЗ_ЧАША_ЧУЧУЛИГА',
      dotCase: 'четири.чучулига.чачаха.червен.чай.чрез.чаша.чучулига',
      lowerCase: 'четири чучулига чачаха червен чай чрез чаша чучулига',
      upperCase: 'ЧЕТИРИ ЧУЧУЛИГА ЧАЧАХА ЧЕРВЕН ЧАЙ ЧРЕЗ ЧАША ЧУЧУЛИГА',
      noAccents: 'Четири чучулига чачаха червен чаи чрез чаша чучулига',
      paramCase: 'четири-чучулига-чачаха-червен-чай-чрез-чаша-чучулига',
      pascalCase: 'ЧетириЧучулигаЧачахаЧервенЧайЧрезЧашаЧучулига',
      snakeCase: 'четири_чучулига_чачаха_червен_чай_чрез_чаша_чучулига',
      toggleCase: 'чЕТИРИ ЧУЧУЛИГА ЧАЧАХА ЧЕРВЕН ЧАЙ ЧРЕЗ ЧАША ЧУЧУЛИГА',
      sentenceCase: 'Четири чучулига чачаха червен чай чрез чаша чучулига',
    },
  },
  {
    scenario: 'Lithuanian',
    source: 'Šešios žąsys su šešiais žąsiukais.',
    tokens: [
      {index: 0, value: 'Šešios', break: ' '},
      {index: 7, value: 'žąsys', break: ' '},
      {index: 13, value: 'su', break: ' '},
      {index: 16, value: 'šešiais', break: ' '},
      {index: 24, value: 'žąsiukais', break: '.'},
    ],
    expected: {
      camelCase: 'šešiosŽąsysSuŠešiaisŽąsiukais',
      constantCase: 'ŠEŠIOS_ŽĄSYS_SU_ŠEŠIAIS_ŽĄSIUKAIS',
      dotCase: 'šešios.žąsys.su.šešiais.žąsiukais',
      lowerCase: 'šešios žąsys su šešiais žąsiukais.',
      upperCase: 'ŠEŠIOS ŽĄSYS SU ŠEŠIAIS ŽĄSIUKAIS.',
      noAccents: 'Sesios zasys su sesiais zasiukais.',
      paramCase: 'šešios-žąsys-su-šešiais-žąsiukais',
      pascalCase: 'ŠešiosŽąsysSuŠešiaisŽąsiukais',
      snakeCase: 'šešios_žąsys_su_šešiais_žąsiukais',
      toggleCase: 'šEŠIOS ŽĄSYS SU ŠEŠIAIS ŽĄSIUKAIS.',
      sentenceCase: 'Šešios žąsys su šešiais žąsiukais.',
    },
  },
  {
    scenario: 'Latvian',
    source: 'Dzīvē dzīvo dzīvu dzīvi! Dzīvam dzīvē dzīva dzīve.',
    tokens: [
      {index: 0, value: 'Dzīvē', break: ' '},
      {index: 6, value: 'dzīvo', break: ' '},
      {index: 12, value: 'dzīvu', break: ' '},
      {index: 18, value: 'dzīvi', break: '!'},
      {index: 24, value: '', break: ' '},
      {index: 25, value: 'Dzīvam', break: ' '},
      {index: 32, value: 'dzīvē', break: ' '},
      {index: 38, value: 'dzīva', break: ' '},
      {index: 44, value: 'dzīve', break: '.'},
    ],
    expected: {
      camelCase: 'dzīvēDzīvoDzīvuDzīviDzīvamDzīvēDzīvaDzīve',
      constantCase: 'DZĪVĒ_DZĪVO_DZĪVU_DZĪVI_DZĪVAM_DZĪVĒ_DZĪVA_DZĪVE',
      dotCase: 'dzīvē.dzīvo.dzīvu.dzīvi.dzīvam.dzīvē.dzīva.dzīve',
      lowerCase: 'dzīvē dzīvo dzīvu dzīvi! dzīvam dzīvē dzīva dzīve.',
      upperCase: 'DZĪVĒ DZĪVO DZĪVU DZĪVI! DZĪVAM DZĪVĒ DZĪVA DZĪVE.',
      noAccents: 'Dzive dzivo dzivu dzivi! Dzivam dzive dziva dzive.',
      paramCase: 'dzīvē-dzīvo-dzīvu-dzīvi-dzīvam-dzīvē-dzīva-dzīve',
      pascalCase: 'DzīvēDzīvoDzīvuDzīviDzīvamDzīvēDzīvaDzīve',
      snakeCase: 'dzīvē_dzīvo_dzīvu_dzīvi_dzīvam_dzīvē_dzīva_dzīve',
      toggleCase: 'dZĪVĒ DZĪVO DZĪVU DZĪVI! dZĪVAM DZĪVĒ DZĪVA DZĪVE.',
      sentenceCase: 'Dzīvē dzīvo dzīvu dzīvi! Dzīvam dzīvē dzīva dzīve.',
    },
  },
  {
    scenario: 'Serbian',
    source: 'Najčvršći potrčko često trči čvrsto četvrtkom u Brčko.',
    tokens: [
      {index: 0, value: 'Najčvršći', break: ' '},
      {index: 10, value: 'potrčko', break: ' '},
      {index: 18, value: 'često', break: ' '},
      {index: 24, value: 'trči', break: ' '},
      {index: 29, value: 'čvrsto', break: ' '},
      {index: 36, value: 'četvrtkom', break: ' '},
      {index: 46, value: 'u', break: ' '},
      {index: 48, value: 'Brčko', break: '.'},
    ],
    expected: {
      camelCase: 'najčvršćiPotrčkoČestoTrčiČvrstoČetvrtkomUBrčko',
      constantCase: 'NAJČVRŠĆI_POTRČKO_ČESTO_TRČI_ČVRSTO_ČETVRTKOM_U_BRČKO',
      dotCase: 'najčvršći.potrčko.često.trči.čvrsto.četvrtkom.u.brčko',
      lowerCase: 'najčvršći potrčko često trči čvrsto četvrtkom u brčko.',
      upperCase: 'NAJČVRŠĆI POTRČKO ČESTO TRČI ČVRSTO ČETVRTKOM U BRČKO.',
      noAccents: 'Najcvrsci potrcko cesto trci cvrsto cetvrtkom u Brcko.',
      paramCase: 'najčvršći-potrčko-često-trči-čvrsto-četvrtkom-u-brčko',
      pascalCase: 'NajčvršćiPotrčkoČestoTrčiČvrstoČetvrtkomUBrčko',
      snakeCase: 'najčvršći_potrčko_često_trči_čvrsto_četvrtkom_u_brčko',
      toggleCase: 'nAJČVRŠĆI POTRČKO ČESTO TRČI ČVRSTO ČETVRTKOM U bRČKO.',
      sentenceCase: 'Najčvršći potrčko često trči čvrsto četvrtkom u brčko.',
    },
  },
  {
    scenario: 'Persian',
    source: 'dâei châgh-e, châi dâgh-e',
    tokens: [
      {index: 0, value: 'dâei', break: ' '},
      {index: 5, value: 'châgh', break: '-'},
      {index: 11, value: 'e', break: ','},
      {index: 13, value: '', break: ' '},
      {index: 14, value: 'châi', break: ' '},
      {index: 19, value: 'dâgh', break: '-'},
      {index: 24, value: 'e', break: ''},
    ],
    expected: {
      camelCase: 'dâeiChâghEChâiDâghE',
      constantCase: 'DÂEI_CHÂGH_E_CHÂI_DÂGH_E',
      dotCase: 'dâei.châgh.e.châi.dâgh.e',
      lowerCase: 'dâei châgh-e, châi dâgh-e',
      upperCase: 'DÂEI CHÂGH-E, CHÂI DÂGH-E',
      noAccents: 'daei chagh-e, chai dagh-e',
      paramCase: 'dâei-châgh-e-châi-dâgh-e',
      pascalCase: 'DâeiChâghEChâiDâghE',
      snakeCase: 'dâei_châgh_e_châi_dâgh_e',
      toggleCase: 'DÂEI CHÂGH-E, CHÂI DÂGH-E',
      sentenceCase: 'Dâei châgh-e, châi dâgh-e',
    },
  },
] as const;
